INSERT INTO `category` (`id`, `name`, `imageFile`) VALUES
(2, 'Computers', 'category/computers.png'),
(3, 'Gaming', 'category/gaming.png'),
(4, 'Headphones', 'category/headphones.png'),
(5, 'Keyboards', 'category/keyboards.png'),
(6, 'Laptops', 'category/laptops.png'),
(7, 'Monitors', 'category/monitors.png'),
(8, 'Mouses', 'category/mouses.png'),
(9, 'Smartphones', 'category/smartphones.png');

INSERT INTO `city` (`zipCode`, `name`) VALUES
(555, 'Scanning'),
(800, 'Høje Taastrup'),
(877, 'Valby'),
(900, 'København C'),
(910, 'København C'),
(929, 'København C'),
(999, 'København C'),
(1000, 'København K'),
(1001, 'København K'),
(1002, 'København K'),
(1003, 'København K'),
(1004, 'København K'),
(1005, 'København K'),
(1006, 'København K'),
(1007, 'København K'),
(1008, 'København K'),
(1009, 'København K'),
(1010, 'København K'),
(1011, 'København K'),
(1012, 'København K'),
(1013, 'København K'),
(1014, 'København K'),
(1015, 'København K'),
(1016, 'København K'),
(1017, 'København K'),
(1018, 'København K'),
(1019, 'København K'),
(1020, 'København K'),
(1021, 'København K'),
(1022, 'København K'),
(1023, 'København K'),
(1024, 'København K'),
(1025, 'København K'),
(1026, 'København K'),
(1045, 'København K'),
(1050, 'København K'),
(1051, 'København K'),
(1052, 'København K'),
(1053, 'København K'),
(1054, 'København K'),
(1055, 'København K'),
(1056, 'København K'),
(1057, 'København K'),
(1058, 'København K'),
(1059, 'København K'),
(1060, 'København K'),
(1061, 'København K'),
(1062, 'København K'),
(1063, 'København K'),
(1064, 'København K'),
(1065, 'København K'),
(1066, 'København K'),
(1067, 'København K'),
(1068, 'København K'),
(1069, 'København K'),
(1070, 'København K'),
(1071, 'København K'),
(1072, 'København K'),
(1073, 'København K'),
(1074, 'København K'),
(1092, 'København K'),
(1093, 'København K'),
(1095, 'København K'),
(1098, 'København K'),
(1100, 'København K'),
(1101, 'København K'),
(1102, 'København K'),
(1103, 'København K'),
(1104, 'København K'),
(1105, 'København K'),
(1106, 'København K'),
(1107, 'København K'),
(1110, 'København K'),
(1111, 'København K'),
(1112, 'København K'),
(1113, 'København K'),
(1114, 'København K'),
(1115, 'København K'),
(1116, 'København K'),
(1117, 'København K'),
(1118, 'København K'),
(1119, 'København K'),
(1120, 'København K'),
(1121, 'København K'),
(1122, 'København K'),
(1123, 'København K'),
(1124, 'København K'),
(1125, 'København K'),
(1126, 'København K'),
(1127, 'København K'),
(1128, 'København K'),
(1129, 'København K'),
(1130, 'København K'),
(1131, 'København K'),
(1140, 'København K'),
(1147, 'København K'),
(1148, 'København K'),
(1150, 'København K'),
(1151, 'København K'),
(1152, 'København K'),
(1153, 'København K'),
(1154, 'København K'),
(1155, 'København K'),
(1156, 'København K'),
(1157, 'København K'),
(1158, 'København K'),
(1159, 'København K'),
(1160, 'København K'),
(1161, 'København K'),
(1162, 'København K'),
(1163, 'København K'),
(1164, 'København K'),
(1165, 'København K'),
(1166, 'København K'),
(1167, 'København K'),
(1168, 'København K'),
(1169, 'København K'),
(1170, 'København K'),
(1171, 'København K'),
(1172, 'København K'),
(1173, 'København K'),
(1174, 'København K'),
(1175, 'København K'),
(1200, 'København K'),
(1201, 'København K'),
(1202, 'København K'),
(1203, 'København K'),
(1204, 'København K'),
(1205, 'København K'),
(1206, 'København K'),
(1207, 'København K'),
(1208, 'København K'),
(1209, 'København K'),
(1210, 'København K'),
(1211, 'København K'),
(1212, 'København K'),
(1213, 'København K'),
(1214, 'København K'),
(1215, 'København K'),
(1216, 'København K'),
(1217, 'København K'),
(1218, 'København K'),
(1219, 'København K'),
(1220, 'København K'),
(1240, 'København K'),
(1250, 'København K'),
(1251, 'København K'),
(1252, 'København K'),
(1253, 'København K'),
(1254, 'København K'),
(1255, 'København K'),
(1256, 'København K'),
(1257, 'København K'),
(1258, 'København K'),
(1259, 'København K'),
(1260, 'København K'),
(1261, 'København K'),
(1263, 'København K'),
(1264, 'København K'),
(1265, 'København K'),
(1266, 'København K'),
(1267, 'København K'),
(1268, 'København K'),
(1270, 'København K'),
(1271, 'København K'),
(1291, 'København K'),
(1300, 'København K'),
(1301, 'København K'),
(1302, 'København K'),
(1303, 'København K'),
(1304, 'København K'),
(1306, 'København K'),
(1307, 'København K'),
(1308, 'København K'),
(1309, 'København K'),
(1310, 'København K'),
(1311, 'København K'),
(1312, 'København K'),
(1313, 'København K'),
(1314, 'København K'),
(1315, 'København K'),
(1316, 'København K'),
(1317, 'København K'),
(1318, 'København K'),
(1319, 'København K'),
(1320, 'København K'),
(1321, 'København K'),
(1322, 'København K'),
(1323, 'København K'),
(1324, 'København K'),
(1325, 'København K'),
(1326, 'København K'),
(1327, 'København K'),
(1328, 'København K'),
(1329, 'København K'),
(1349, 'København K'),
(1350, 'København K'),
(1352, 'København K'),
(1353, 'København K'),
(1354, 'København K'),
(1355, 'København K'),
(1356, 'København K'),
(1357, 'København K'),
(1358, 'København K'),
(1359, 'København K'),
(1360, 'København K'),
(1361, 'København K'),
(1362, 'København K'),
(1363, 'København K'),
(1364, 'København K'),
(1365, 'København K'),
(1366, 'København K'),
(1367, 'København K'),
(1368, 'København K'),
(1369, 'København K'),
(1370, 'København K'),
(1371, 'København K'),
(1390, 'København K'),
(1400, 'København K'),
(1401, 'København K'),
(1402, 'København K'),
(1403, 'København K'),
(1404, 'København K'),
(1405, 'København K'),
(1406, 'København K'),
(1407, 'København K'),
(1408, 'København K'),
(1409, 'København K'),
(1410, 'København K'),
(1411, 'København K'),
(1412, 'København K'),
(1413, 'København K'),
(1414, 'København K'),
(1415, 'København K'),
(1416, 'København K'),
(1417, 'København K'),
(1418, 'København K'),
(1419, 'København K'),
(1420, 'København K'),
(1421, 'København K'),
(1422, 'København K'),
(1423, 'København K'),
(1424, 'København K'),
(1425, 'København K'),
(1426, 'København K'),
(1427, 'København K'),
(1428, 'København K'),
(1429, 'København K'),
(1430, 'København K'),
(1431, 'København K'),
(1432, 'København K'),
(1433, 'København K'),
(1434, 'København K'),
(1435, 'København K'),
(1436, 'København K'),
(1437, 'København K'),
(1438, 'København K'),
(1439, 'København K'),
(1440, 'København K'),
(1441, 'København K'),
(1448, 'København K'),
(1450, 'København K'),
(1451, 'København K'),
(1452, 'København K'),
(1453, 'København K'),
(1454, 'København K'),
(1455, 'København K'),
(1456, 'København K'),
(1457, 'København K'),
(1458, 'København K'),
(1459, 'København K'),
(1460, 'København K'),
(1461, 'København K'),
(1462, 'København K'),
(1463, 'København K'),
(1464, 'København K'),
(1465, 'København K'),
(1466, 'København K'),
(1467, 'København K'),
(1468, 'København K'),
(1470, 'København K'),
(1471, 'København K'),
(1472, 'København K'),
(1473, 'København K'),
(1500, 'København V'),
(1501, 'København V'),
(1502, 'København V'),
(1503, 'København V'),
(1504, 'København V'),
(1505, 'København V'),
(1506, 'København V'),
(1507, 'København V'),
(1508, 'København V'),
(1509, 'København V'),
(1510, 'København V'),
(1532, 'København V'),
(1533, 'København V'),
(1550, 'København V'),
(1551, 'København V'),
(1552, 'København V'),
(1553, 'København V'),
(1554, 'København V'),
(1555, 'København V'),
(1556, 'København V'),
(1557, 'København V'),
(1558, 'København V'),
(1559, 'København V'),
(1560, 'København V'),
(1561, 'København V'),
(1562, 'København V'),
(1563, 'København V'),
(1564, 'København V'),
(1566, 'København V'),
(1567, 'København V'),
(1568, 'København V'),
(1569, 'København V'),
(1570, 'København V'),
(1571, 'København V'),
(1572, 'København V'),
(1573, 'København V'),
(1574, 'København V'),
(1575, 'København V'),
(1576, 'København V'),
(1577, 'København V'),
(1590, 'København V'),
(1592, 'København V'),
(1599, 'København V'),
(1600, 'København V'),
(1601, 'København V'),
(1602, 'København V'),
(1603, 'København V'),
(1604, 'København V'),
(1605, 'København V'),
(1606, 'København V'),
(1607, 'København V'),
(1608, 'København V'),
(1609, 'København V'),
(1610, 'København V'),
(1611, 'København V'),
(1612, 'København V'),
(1613, 'København V'),
(1614, 'København V'),
(1615, 'København V'),
(1616, 'København V'),
(1617, 'København V'),
(1618, 'København V'),
(1619, 'København V'),
(1620, 'København V'),
(1621, 'København V'),
(1622, 'København V'),
(1623, 'København V'),
(1624, 'København V'),
(1630, 'København V'),
(1631, 'København V'),
(1632, 'København V'),
(1633, 'København V'),
(1634, 'København V'),
(1635, 'København V'),
(1639, 'København V'),
(1640, 'København V'),
(1650, 'København V'),
(1651, 'København V'),
(1652, 'København V'),
(1653, 'København V'),
(1654, 'København V'),
(1655, 'København V'),
(1656, 'København V'),
(1657, 'København V'),
(1658, 'København V'),
(1659, 'København V'),
(1660, 'København V'),
(1661, 'København V'),
(1662, 'København V'),
(1663, 'København V'),
(1664, 'København V'),
(1665, 'København V'),
(1666, 'København V'),
(1667, 'København V'),
(1668, 'København V'),
(1669, 'København V'),
(1670, 'København V'),
(1671, 'København V'),
(1672, 'København V'),
(1673, 'København V'),
(1674, 'København V'),
(1675, 'København V'),
(1676, 'København V'),
(1677, 'København V'),
(1699, 'København V'),
(1700, 'København V'),
(1701, 'København V'),
(1702, 'København V'),
(1703, 'København V'),
(1704, 'København V'),
(1705, 'København V'),
(1706, 'København V'),
(1707, 'København V'),
(1708, 'København V'),
(1709, 'København V'),
(1710, 'København V'),
(1711, 'København V'),
(1712, 'København V'),
(1713, 'København V'),
(1714, 'København V'),
(1715, 'København V'),
(1716, 'København V'),
(1717, 'København V'),
(1718, 'København V'),
(1719, 'København V'),
(1720, 'København V'),
(1721, 'København V'),
(1722, 'København V'),
(1723, 'København V'),
(1724, 'København V'),
(1725, 'København V'),
(1726, 'København V'),
(1727, 'København V'),
(1728, 'København V'),
(1729, 'København V'),
(1730, 'København V'),
(1731, 'København V'),
(1732, 'København V'),
(1733, 'København V'),
(1734, 'København V'),
(1735, 'København V'),
(1736, 'København V'),
(1737, 'København V'),
(1738, 'København V'),
(1739, 'København V'),
(1748, 'København V'),
(1749, 'København V'),
(1750, 'København V'),
(1751, 'København V'),
(1752, 'København V'),
(1753, 'København V'),
(1754, 'København V'),
(1755, 'København V'),
(1756, 'København V'),
(1757, 'København V'),
(1758, 'København V'),
(1759, 'København V'),
(1760, 'København V'),
(1761, 'København V'),
(1762, 'København V'),
(1763, 'København V'),
(1764, 'København V'),
(1765, 'København V'),
(1766, 'København V'),
(1770, 'København V'),
(1771, 'København V'),
(1772, 'København V'),
(1773, 'København V'),
(1774, 'København V'),
(1775, 'København V'),
(1777, 'København V'),
(1778, 'København V'),
(1780, 'København V'),
(1782, 'København V'),
(1784, 'København V'),
(1785, 'København V'),
(1786, 'København V'),
(1787, 'København V'),
(1788, 'København V'),
(1789, 'København V'),
(1790, 'København V'),
(1795, 'København V'),
(1799, 'København V'),
(1800, 'Frederiksberg C'),
(1801, 'Frederiksberg C'),
(1802, 'Frederiksberg C'),
(1803, 'Frederiksberg C'),
(1804, 'Frederiksberg C'),
(1805, 'Frederiksberg C'),
(1806, 'Frederiksberg C'),
(1807, 'Frederiksberg C'),
(1808, 'Frederiksberg C'),
(1809, 'Frederiksberg C'),
(1810, 'Frederiksberg C'),
(1811, 'Frederiksberg C'),
(1812, 'Frederiksberg C'),
(1813, 'Frederiksberg C'),
(1814, 'Frederiksberg C'),
(1815, 'Frederiksberg C'),
(1816, 'Frederiksberg C'),
(1817, 'Frederiksberg C'),
(1818, 'Frederiksberg C'),
(1819, 'Frederiksberg C'),
(1820, 'Frederiksberg C'),
(1822, 'Frederiksberg C'),
(1823, 'Frederiksberg C'),
(1824, 'Frederiksberg C'),
(1825, 'Frederiksberg C'),
(1826, 'Frederiksberg C'),
(1827, 'Frederiksberg C'),
(1828, 'Frederiksberg C'),
(1829, 'Frederiksberg C'),
(1835, 'Frederiksberg C'),
(1850, 'Frederiksberg C'),
(1851, 'Frederiksberg C'),
(1852, 'Frederiksberg C'),
(1853, 'Frederiksberg C'),
(1854, 'Frederiksberg C'),
(1855, 'Frederiksberg C'),
(1856, 'Frederiksberg C'),
(1857, 'Frederiksberg C'),
(1860, 'Frederiksberg C'),
(1861, 'Frederiksberg C'),
(1862, 'Frederiksberg C'),
(1863, 'Frederiksberg C'),
(1864, 'Frederiksberg C'),
(1865, 'Frederiksberg C'),
(1866, 'Frederiksberg C'),
(1867, 'Frederiksberg C'),
(1868, 'Frederiksberg C'),
(1870, 'Frederiksberg C'),
(1871, 'Frederiksberg C'),
(1872, 'Frederiksberg C'),
(1873, 'Frederiksberg C'),
(1874, 'Frederiksberg C'),
(1875, 'Frederiksberg C'),
(1876, 'Frederiksberg C'),
(1877, 'Frederiksberg C'),
(1878, 'Frederiksberg C'),
(1879, 'Frederiksberg C'),
(1900, 'Frederiksberg C'),
(1901, 'Frederiksberg C'),
(1902, 'Frederiksberg C'),
(1903, 'Frederiksberg C'),
(1904, 'Frederiksberg C'),
(1905, 'Frederiksberg C'),
(1906, 'Frederiksberg C'),
(1908, 'Frederiksberg C'),
(1909, 'Frederiksberg C'),
(1910, 'Frederiksberg C'),
(1911, 'Frederiksberg C'),
(1912, 'Frederiksberg C'),
(1913, 'Frederiksberg C'),
(1914, 'Frederiksberg C'),
(1915, 'Frederiksberg C'),
(1916, 'Frederiksberg C'),
(1917, 'Frederiksberg C'),
(1920, 'Frederiksberg C'),
(1921, 'Frederiksberg C'),
(1922, 'Frederiksberg C'),
(1923, 'Frederiksberg C'),
(1924, 'Frederiksberg C'),
(1925, 'Frederiksberg C'),
(1926, 'Frederiksberg C'),
(1927, 'Frederiksberg C'),
(1928, 'Frederiksberg C'),
(1931, 'Frederiksberg C'),
(1950, 'Frederiksberg C'),
(1951, 'Frederiksberg C'),
(1952, 'Frederiksberg C'),
(1953, 'Frederiksberg C'),
(1954, 'Frederiksberg C'),
(1955, 'Frederiksberg C'),
(1956, 'Frederiksberg C'),
(1957, 'Frederiksberg C'),
(1958, 'Frederiksberg C'),
(1959, 'Frederiksberg C'),
(1960, 'Frederiksberg C'),
(1961, 'Frederiksberg C'),
(1962, 'Frederiksberg C'),
(1963, 'Frederiksberg C'),
(1964, 'Frederiksberg C'),
(1965, 'Frederiksberg C'),
(1966, 'Frederiksberg C'),
(1967, 'Frederiksberg C'),
(1970, 'Frederiksberg C'),
(1971, 'Frederiksberg C'),
(1972, 'Frederiksberg C'),
(1973, 'Frederiksberg C'),
(1974, 'Frederiksberg C'),
(1999, 'Frederiksberg C'),
(2000, 'Frederiksberg'),
(2100, 'København Ø'),
(2200, 'København N'),
(2300, 'København S'),
(2400, 'København NV'),
(2450, 'København SV'),
(2500, 'Valby'),
(2600, 'Glostrup'),
(2605, 'Brøndby'),
(2610, 'Rødovre'),
(2620, 'Albertslund'),
(2625, 'Vallensbæk'),
(2630, 'Taastrup'),
(2635, 'Ishøj'),
(2640, 'Hedehusene'),
(2650, 'Hvidovre'),
(2660, 'Brøndby Strand'),
(2665, 'Vallensbæk Strand'),
(2670, 'Greve'),
(2680, 'Solrød Strand'),
(2690, 'Karlslunde'),
(2700, 'Brønshøj'),
(2720, 'Vanløse'),
(2730, 'Herlev'),
(2740, 'Skovlunde'),
(2750, 'Ballerup'),
(2760, 'Måløv'),
(2765, 'Smørum'),
(2770, 'Kastrup'),
(2791, 'Dragør'),
(2800, 'Kongens Lyngby'),
(2820, 'Gentofte'),
(2830, 'Virum'),
(2840, 'Holte'),
(2850, 'Nærum'),
(2860, 'Søborg'),
(2870, 'Dyssegård'),
(2880, 'Bagsværd'),
(2900, 'Hellerup'),
(2920, 'Charlottenlund'),
(2930, 'Klampenborg'),
(2942, 'Skodsborg'),
(2950, 'Vedbæk'),
(2960, 'Rungsted Kyst'),
(2970, 'Hørsholm'),
(2980, 'Kokkedal'),
(2990, 'Nivå'),
(3000, 'Helsingør'),
(3050, 'Humlebæk'),
(3060, 'Espergærde'),
(3070, 'Snekkersten'),
(3080, 'Tikøb'),
(3100, 'Hornbæk'),
(3120, 'Dronningmølle'),
(3140, 'Ålsgårde'),
(3150, 'Hellebæk'),
(3200, 'Helsinge'),
(3210, 'Vejby'),
(3220, 'Tisvildeleje'),
(3230, 'Græsted'),
(3250, 'Gilleleje'),
(3300, 'Frederiksværk'),
(3310, 'Ølsted'),
(3320, 'Skævinge'),
(3330, 'Gørløse'),
(3360, 'Liseleje'),
(3370, 'Melby'),
(3390, 'Hundested'),
(3400, 'Hillerød'),
(3450, 'Allerød'),
(3460, 'Birkerød'),
(3480, 'Fredensborg'),
(3490, 'Kvistgård'),
(3500, 'Værløse'),
(3520, 'Farum'),
(3540, 'Lynge'),
(3550, 'Slangerup'),
(3600, 'Frederikssund'),
(3630, 'Jægerspris'),
(3650, 'Ølstykke'),
(3660, 'Stenløse'),
(3670, 'Veksø Sjælland'),
(3700, 'Rønne'),
(3720, 'Aakirkeby'),
(3730, 'Nexø'),
(3740, 'Svaneke'),
(3751, 'Østermarie'),
(3760, 'Gudhjem'),
(3770, 'Allinge'),
(3782, 'Klemensker'),
(3790, 'Hasle'),
(4000, 'Roskilde'),
(4040, 'Jyllinge'),
(4050, 'Skibby'),
(4060, 'Kirke Såby'),
(4070, 'Kirke Hyllinge'),
(4100, 'Ringsted'),
(4105, 'Ringsted'),
(4129, 'Ringsted'),
(4130, 'Viby Sjælland'),
(4140, 'Borup'),
(4160, 'Herlufmagle'),
(4171, 'Glumsø'),
(4173, 'Fjenneslev'),
(4174, 'Jystrup Midtsj'),
(4180, 'Sorø'),
(4190, 'Munke Bjergby'),
(4200, 'Slagelse'),
(4220, 'Korsør'),
(4230, 'Skælskør'),
(4241, 'Vemmelev'),
(4242, 'Boeslunde'),
(4243, 'Rude'),
(4250, 'Fuglebjerg'),
(4261, 'Dalmose'),
(4262, 'Sandved'),
(4270, 'Høng'),
(4281, 'Gørlev'),
(4291, 'Ruds Vedby'),
(4293, 'Dianalund'),
(4295, 'Stenlille'),
(4296, 'Nyrup'),
(4300, 'Holbæk'),
(4320, 'Lejre'),
(4330, 'Hvalsø'),
(4340, 'Tølløse'),
(4350, 'Ugerløse'),
(4360, 'Kirke Eskilstrup'),
(4370, 'Store Merløse'),
(4390, 'Vipperød'),
(4400, 'Kalundborg'),
(4420, 'Regstrup'),
(4440, 'Mørkøv'),
(4450, 'Jyderup'),
(4460, 'Snertinge'),
(4470, 'Svebølle'),
(4480, 'Store Fuglede'),
(4490, 'Jerslev Sjælland'),
(4500, 'Nykøbing Sj'),
(4520, 'Svinninge'),
(4532, 'Gislinge'),
(4534, 'Hørve'),
(4540, 'Fårevejle'),
(4550, 'Asnæs'),
(4560, 'Vig'),
(4571, 'Grevinge'),
(4572, 'Nørre Asmindrup'),
(4573, 'Højby'),
(4581, 'Rørvig'),
(4583, 'Sjællands Odde'),
(4591, 'Føllenslev'),
(4592, 'Sejerø'),
(4593, 'Eskebjerg'),
(4600, 'Køge'),
(4621, 'Gadstrup'),
(4622, 'Havdrup'),
(4623, 'Lille Skensved'),
(4632, 'Bjæverskov'),
(4640, 'Faxe'),
(4652, 'Hårlev'),
(4653, 'Karise'),
(4654, 'Faxe Ladeplads'),
(4660, 'Store Heddinge'),
(4671, 'Strøby'),
(4672, 'Klippinge'),
(4673, 'Rødvig Stevns'),
(4681, 'Herfølge'),
(4682, 'Tureby'),
(4683, 'Rønnede'),
(4684, 'Holmegaard'),
(4690, 'Haslev'),
(4700, 'Næstved'),
(4720, 'Præstø'),
(4733, 'Tappernøje'),
(4735, 'Mern'),
(4736, 'Karrebæksminde'),
(4750, 'Lundby'),
(4760, 'Vordingborg'),
(4771, 'Kalvehave'),
(4772, 'Langebæk'),
(4773, 'Stensved'),
(4780, 'Stege'),
(4791, 'Borre'),
(4792, 'Askeby'),
(4793, 'Bogø By'),
(4800, 'Nykøbing F'),
(4840, 'Nørre Alslev'),
(4850, 'Stubbekøbing'),
(4862, 'Guldborg'),
(4863, 'Eskilstrup'),
(4871, 'Horbelev'),
(4872, 'Idestrup'),
(4873, 'Væggerløse'),
(4874, 'Gedser'),
(4880, 'Nysted'),
(4891, 'Toreby L'),
(4892, 'Kettinge'),
(4894, 'Øster Ulslev'),
(4895, 'Errindlev'),
(4900, 'Nakskov'),
(4912, 'Harpelunde'),
(4913, 'Horslunde'),
(4920, 'Søllested'),
(4930, 'Maribo'),
(4941, 'Bandholm'),
(4943, 'Torrig L'),
(4944, 'Fejø'),
(4951, 'Nørreballe'),
(4952, 'Stokkemarke'),
(4953, 'Vesterborg'),
(4960, 'Holeby'),
(4970, 'Rødby'),
(4983, 'Dannemare'),
(4990, 'Sakskøbing'),
(5000, 'Odense C'),
(5029, 'Odense C'),
(5090, 'Odense C'),
(5100, 'Odense C'),
(5200, 'Odense V'),
(5210, 'Odense NV'),
(5220, 'Odense SØ'),
(5230, 'Odense M'),
(5240, 'Odense NØ'),
(5250, 'Odense SV'),
(5260, 'Odense S'),
(5270, 'Odense N'),
(5290, 'Marslev'),
(5300, 'Kerteminde'),
(5320, 'Agedrup'),
(5330, 'Munkebo'),
(5350, 'Rynkeby'),
(5370, 'Mesinge'),
(5380, 'Dalby'),
(5390, 'Martofte'),
(5400, 'Bogense'),
(5450, 'Otterup'),
(5462, 'Morud'),
(5463, 'Harndrup'),
(5464, 'Brenderup Fyn'),
(5466, 'Asperup'),
(5471, 'Søndersø'),
(5474, 'Veflinge'),
(5485, 'Skamby'),
(5491, 'Blommenslyst'),
(5492, 'Vissenbjerg'),
(5500, 'Middelfart'),
(5540, 'Ullerslev'),
(5550, 'Langeskov'),
(5560, 'Aarup'),
(5580, 'Nørre Aaby'),
(5591, 'Gelsted'),
(5592, 'Ejby'),
(5600, 'Faaborg'),
(5610, 'Assens'),
(5620, 'Glamsbjerg'),
(5631, 'Ebberup'),
(5642, 'Millinge'),
(5672, 'Broby'),
(5683, 'Haarby'),
(5690, 'Tommerup'),
(5700, 'Svendborg'),
(5750, 'Ringe'),
(5762, 'Vester Skerninge'),
(5771, 'Stenstrup'),
(5772, 'Kværndrup'),
(5792, 'Årslev'),
(5800, 'Nyborg'),
(5853, 'Ørbæk'),
(5854, 'Gislev'),
(5856, 'Ryslinge'),
(5863, 'Ferritslev Fyn'),
(5871, 'Frørup'),
(5874, 'Hesselager'),
(5881, 'Skårup Fyn'),
(5882, 'Vejstrup'),
(5883, 'Oure'),
(5884, 'Gudme'),
(5892, 'Gudbjerg Sydfyn'),
(5900, 'Rudkøbing'),
(5932, 'Humble'),
(5935, 'Bagenkop'),
(5953, 'Tranekær'),
(5960, 'Marstal'),
(5970, 'Ærøskøbing'),
(5985, 'Søby Ærø'),
(6000, 'Kolding'),
(6040, 'Egtved'),
(6051, 'Almind'),
(6052, 'Viuf'),
(6064, 'Jordrup'),
(6070, 'Christiansfeld'),
(6091, 'Bjert'),
(6092, 'Sønder Stenderup'),
(6093, 'Sjølund'),
(6094, 'Hejls'),
(6100, 'Haderslev'),
(6200, 'Aabenraa'),
(6230, 'Rødekro'),
(6240, 'Løgumkloster'),
(6261, 'Bredebro'),
(6270, 'Tønder'),
(6280, 'Højer'),
(6300, 'Gråsten'),
(6310, 'Broager'),
(6320, 'Egernsund'),
(6330, 'Padborg'),
(6340, 'Kruså'),
(6360, 'Tinglev'),
(6372, 'Bylderup-Bov'),
(6392, 'Bolderslev'),
(6400, 'Sønderborg'),
(6430, 'Nordborg'),
(6440, 'Augustenborg'),
(6470, 'Sydals'),
(6500, 'Vojens'),
(6510, 'Gram'),
(6520, 'Toftlund'),
(6534, 'Agerskov'),
(6535, 'Branderup J'),
(6541, 'Bevtoft'),
(6560, 'Sommersted'),
(6580, 'Vamdrup'),
(6600, 'Vejen'),
(6621, 'Gesten'),
(6622, 'Bække'),
(6623, 'Vorbasse'),
(6630, 'Rødding'),
(6640, 'Lunderskov'),
(6650, 'Brørup'),
(6660, 'Lintrup'),
(6670, 'Holsted'),
(6682, 'Hovborg'),
(6683, 'Føvling'),
(6690, 'Gørding'),
(6700, 'Esbjerg'),
(6701, 'Esbjerg'),
(6705, 'Esbjerg Ø'),
(6710, 'Esbjerg V'),
(6715, 'Esbjerg N'),
(6720, 'Fanø'),
(6731, 'Tjæreborg'),
(6740, 'Bramming'),
(6752, 'Glejbjerg'),
(6753, 'Agerbæk'),
(6760, 'Ribe'),
(6771, 'Gredstedbro'),
(6780, 'Skærbæk'),
(6792, 'Rømø'),
(6800, 'Varde'),
(6818, 'Årre'),
(6823, 'Ansager'),
(6830, 'Nørre Nebel'),
(6840, 'Oksbøl'),
(6851, 'Janderup Vestj'),
(6852, 'Billum'),
(6853, 'Vejers Strand'),
(6854, 'Henne'),
(6855, 'Outrup'),
(6857, 'Blåvand'),
(6862, 'Tistrup'),
(6870, 'Ølgod'),
(6880, 'Tarm'),
(6893, 'Hemmet'),
(6900, 'Skjern'),
(6920, 'Videbæk'),
(6933, 'Kibæk'),
(6940, 'Lem St'),
(6950, 'Ringkøbing'),
(6960, 'Hvide Sande'),
(6971, 'Spjald'),
(6973, 'Ørnhøj'),
(6980, 'Tim'),
(6990, 'Ulfborg'),
(7000, 'Fredericia'),
(7007, 'Fredericia'),
(7029, 'Fredericia'),
(7080, 'Børkop'),
(7100, 'Vejle'),
(7120, 'Vejle Øst'),
(7130, 'Juelsminde'),
(7140, 'Stouby'),
(7150, 'Barrit'),
(7160, 'Tørring'),
(7171, 'Uldum'),
(7173, 'Vonge'),
(7182, 'Bredsten'),
(7183, 'Randbøl'),
(7184, 'Vandel'),
(7190, 'Billund'),
(7200, 'Grindsted'),
(7250, 'Hejnsvig'),
(7260, 'Sønder Omme'),
(7270, 'Stakroge'),
(7280, 'Sønder Felding'),
(7300, 'Jelling'),
(7321, 'Gadbjerg'),
(7323, 'Give'),
(7330, 'Brande'),
(7361, 'Ejstrupholm'),
(7362, 'Hampen'),
(7400, 'Herning'),
(7401, 'Herning'),
(7429, 'Herning'),
(7430, 'Ikast'),
(7441, 'Bording'),
(7442, 'Engesvang'),
(7451, 'Sunds'),
(7470, 'Karup J'),
(7480, 'Vildbjerg'),
(7490, 'Aulum'),
(7500, 'Holstebro'),
(7540, 'Haderup'),
(7550, 'Sørvad'),
(7560, 'Hjerm'),
(7570, 'Vemb'),
(7600, 'Struer'),
(7620, 'Lemvig'),
(7650, 'Bøvlingbjerg'),
(7660, 'Bækmarksbro'),
(7673, 'Harboøre'),
(7680, 'Thyborøn'),
(7700, 'Thisted'),
(7730, 'Hanstholm'),
(7741, 'Frøstrup'),
(7742, 'Vesløs'),
(7752, 'Snedsted'),
(7755, 'Bedsted Thy'),
(7760, 'Hurup Thy'),
(7770, 'Vestervig'),
(7790, 'Thyholm'),
(7800, 'Skive'),
(7830, 'Vinderup'),
(7840, 'Højslev'),
(7850, 'Stoholm Jyll'),
(7860, 'Spøttrup'),
(7870, 'Roslev'),
(7884, 'Fur'),
(7900, 'Nykøbing M'),
(7950, 'Erslev'),
(7960, 'Karby'),
(7970, 'Redsted M'),
(7980, 'Vils'),
(7990, 'Øster Assels'),
(8000, 'Århus C'),
(8100, 'Århus C'),
(8200, 'Århus N'),
(8210, 'Århus V'),
(8220, 'Brabrand'),
(8229, 'Risskov Ø'),
(8230, 'Åbyhøj'),
(8240, 'Risskov'),
(8245, 'Risskov Ø'),
(8250, 'Egå'),
(8260, 'Viby J'),
(8270, 'Højbjerg'),
(8300, 'Odder'),
(8305, 'Samsø'),
(8310, 'Tranbjerg J'),
(8320, 'Mårslet'),
(8330, 'Beder'),
(8340, 'Malling'),
(8350, 'Hundslund'),
(8355, 'Solbjerg'),
(8361, 'Hasselager'),
(8362, 'Hørning'),
(8370, 'Hadsten'),
(8380, 'Trige'),
(8381, 'Tilst'),
(8382, 'Hinnerup'),
(8400, 'Ebeltoft'),
(8410, 'Rønde'),
(8420, 'Knebel'),
(8444, 'Balle'),
(8450, 'Hammel'),
(8462, 'Harlev J'),
(8464, 'Galten'),
(8471, 'Sabro'),
(8472, 'Sporup'),
(8500, 'Grenaa'),
(8520, 'Lystrup'),
(8530, 'Hjortshøj'),
(8541, 'Skødstrup'),
(8543, 'Hornslet'),
(8544, 'Mørke'),
(8550, 'Ryomgård'),
(8560, 'Kolind'),
(8570, 'Trustrup'),
(8581, 'Nimtofte'),
(8585, 'Glesborg'),
(8586, 'Ørum Djurs'),
(8592, 'Anholt'),
(8600, 'Silkeborg'),
(8620, 'Kjellerup'),
(8632, 'Lemming'),
(8641, 'Sorring'),
(8643, 'Ans By'),
(8653, 'Them'),
(8654, 'Bryrup'),
(8660, 'Skanderborg'),
(8670, 'Låsby'),
(8680, 'Ry'),
(8700, 'Horsens'),
(8721, 'Daugård'),
(8722, 'Hedensted'),
(8723, 'Løsning'),
(8732, 'Hovedgård'),
(8740, 'Brædstrup'),
(8751, 'Gedved'),
(8752, 'Østbirk'),
(8762, 'Flemming'),
(8763, 'Rask Mølle'),
(8765, 'Klovborg'),
(8766, 'Nørre Snede'),
(8781, 'Stenderup'),
(8783, 'Hornsyld'),
(8800, 'Viborg'),
(8830, 'Tjele'),
(8831, 'Løgstrup'),
(8832, 'Skals'),
(8840, 'Rødkærsbro'),
(8850, 'Bjerringbro'),
(8860, 'Ulstrup'),
(8870, 'Langå'),
(8881, 'Thorsø'),
(8882, 'Fårvang'),
(8883, 'Gjern'),
(8900, 'Randers'),
(8950, 'Ørsted'),
(8961, 'Allingåbro'),
(8963, 'Auning'),
(8970, 'Havndal'),
(8981, 'Spentrup'),
(8983, 'Gjerlev J'),
(8990, 'Fårup'),
(9000, 'Aalborg'),
(9020, 'Aalborg'),
(9029, 'Aalborg'),
(9100, 'Aalborg'),
(9200, 'Aalborg SV'),
(9210, 'Aalborg SØ'),
(9220, 'Aalborg Øst'),
(9230, 'Svenstrup J'),
(9240, 'Nibe'),
(9260, 'Gistrup'),
(9270, 'Klarup'),
(9280, 'Storvorde'),
(9293, 'Kongerslev'),
(9300, 'Sæby'),
(9310, 'Vodskov'),
(9320, 'Hjallerup'),
(9330, 'Dronninglund'),
(9340, 'Asaa'),
(9352, 'Dybvad'),
(9362, 'Gandrup'),
(9370, 'Hals'),
(9380, 'Vestbjerg'),
(9381, 'Sulsted'),
(9382, 'Tylstrup'),
(9400, 'Nørresundby'),
(9430, 'Vadum'),
(9440, 'Aabybro'),
(9460, 'Brovst'),
(9480, 'Løkken'),
(9490, 'Pandrup'),
(9492, 'Blokhus'),
(9493, 'Saltum'),
(9500, 'Hobro'),
(9510, 'Arden'),
(9520, 'Skørping'),
(9530, 'Støvring'),
(9541, 'Suldrup'),
(9550, 'Mariager'),
(9560, 'Hadsund'),
(9574, 'Bælum'),
(9575, 'Terndrup'),
(9600, 'Aars'),
(9610, 'Nørager'),
(9620, 'Aalestrup'),
(9631, 'Gedsted'),
(9632, 'Møldrup'),
(9640, 'Farsø'),
(9670, 'Løgstør'),
(9681, 'Ranum'),
(9690, 'Fjerritslev'),
(9700, 'Brønderslev'),
(9740, 'Jerslev J'),
(9750, 'Østervrå'),
(9760, 'Vrå'),
(9800, 'Hjørring'),
(9830, 'Tårs'),
(9850, 'Hirtshals'),
(9870, 'Sindal'),
(9881, 'Bindslev'),
(9900, 'Frederikshavn'),
(9940, 'Læsø'),
(9970, 'Strandby'),
(9981, 'Jerup'),
(9982, 'Ålbæk'),
(9990, 'Skagen');

INSERT INTO `country` (`id`, `name`, `ISO3166_Alpha2`) VALUES
(1, 'Aland Islands', 'AX'),
(2, 'Albania', 'AL'),
(3, 'Andorra', 'AD'),
(4, 'Austria', 'AT'),
(5, 'Belarus', 'BY'),
(6, 'Belgium', 'BE'),
(7, 'Bosnia and Herzegovina', 'BA'),
(8, 'Bulgaria', 'BG'),
(9, 'Croatia', 'HR'),
(10, 'Czech Republic', 'CZ'),
(11, 'Denmark', 'DK'),
(12, 'Estonia', 'EE'),
(13, 'Faroe Islands', 'FO'),
(14, 'Finland', 'FI'),
(15, 'France', 'FR'),
(16, 'Germany', 'DE'),
(17, 'Gibraltar', 'GI'),
(18, 'Greece', 'GR'),
(19, 'Guernsey', 'GG'),
(20, 'Holy See (Vatican City State)', 'VA'),
(21, 'Hungary', 'HU'),
(22, 'Iceland', 'IS'),
(23, 'Ireland', 'IE'),
(24, 'Isle of Man', 'IM'),
(25, 'Italy', 'IT'),
(26, 'Jersey', 'JE'),
(27, 'Kosovo', 'XK'),
(28, 'Latvia', 'LV'),
(29, 'Liechtenstein', 'LI'),
(30, 'Lithuania', 'LT'),
(31, 'Luxembourg', 'LU'),
(32, 'Macedonia, the Former Yugoslav Republic of', 'MK'),
(33, 'Malta', 'MT'),
(34, 'Moldova, Republic of', 'MD'),
(35, 'Monaco', 'MC'),
(36, 'Montenegro', 'ME'),
(37, 'Netherlands', 'NL'),
(38, 'Norway', 'NO'),
(39, 'Poland', 'PL'),
(40, 'Portugal', 'PT'),
(41, 'Romania', 'RO'),
(42, 'San Marino', 'SM'),
(43, 'Serbia', 'RS'),
(44, 'Serbia and Montenegro', 'CS'),
(45, 'Slovakia', 'SK'),
(46, 'Slovenia', 'SI'),
(47, 'Spain', 'ES'),
(48, 'Svalbard and Jan Mayen', 'SJ'),
(49, 'Sweden', 'SE'),
(50, 'Switzerland', 'CH'),
(51, 'Ukraine', 'UA'),
(52, 'United Kingdom', 'GB');

INSERT INTO `currency` (`id`, `name`, `ISO4217_ISO`) VALUES
(1, 'Afghan Afghani', 'AFA'),
(2, 'Albanian Lek', 'ALL'),
(3, 'Algerian Dinar', 'DZD'),
(4, 'Angolan Kwanza', 'AOA'),
(5, 'Argentine Peso', 'ARS'),
(6, 'Armenian Dram', 'AMD'),
(7, 'Aruban Florin', 'AWG'),
(8, 'Australian Dollar', 'AUD'),
(9, 'Azerbaijani Manat', 'AZN'),
(10, 'Bahamian Dollar', 'BSD'),
(11, 'Bahraini Dinar', 'BHD'),
(12, 'Bangladeshi Taka', 'BDT'),
(13, 'Barbadian Dollar', 'BBD'),
(14, 'Belarusian Ruble', 'BYR'),
(15, 'Belgian Franc', 'BEF'),
(16, 'Belize Dollar', 'BZD'),
(17, 'Bermudan Dollar', 'BMD'),
(18, 'Bhutanese Ngultrum', 'BTN'),
(19, 'Bitcoin', 'BTC'),
(20, 'Bolivian Boliviano', 'BOB'),
(21, 'Bosnia-Herzegovina Convertible Mark', 'BAM'),
(22, 'Botswanan Pula', 'BWP'),
(23, 'Brazilian Real', 'BRL'),
(24, 'British Pound Sterling', 'GBP'),
(25, 'Brunei Dollar', 'BND'),
(26, 'Bulgarian Lev', 'BGN'),
(27, 'Burundian Franc', 'BIF'),
(28, 'Cambodian Riel', 'KHR'),
(29, 'Canadian Dollar', 'CAD'),
(30, 'Cape Verdean Escudo', 'CVE'),
(31, 'Cayman Islands Dollar', 'KYD'),
(32, 'CFA Franc BCEAO', 'XOF'),
(33, 'CFA Franc BEAC', 'XAF'),
(34, 'CFP Franc', 'XPF'),
(35, 'Chilean Peso', 'CLP'),
(36, 'Chinese Yuan', 'CNY'),
(37, 'Colombian Peso', 'COP'),
(38, 'Comorian Franc', 'KMF'),
(39, 'Congolese Franc', 'CDF'),
(40, 'Costa Rican ColÃ³n', 'CRC'),
(41, 'Croatian Kuna', 'HRK'),
(42, 'Cuban Convertible Peso', 'CUC'),
(43, 'Czech Republic Koruna', 'CZK'),
(44, 'Danish Krone', 'DKK'),
(45, 'Djiboutian Franc', 'DJF'),
(46, 'Dominican Peso', 'DOP'),
(47, 'East Caribbean Dollar', 'XCD'),
(48, 'Egyptian Pound', 'EGP'),
(49, 'Eritrean Nakfa', 'ERN'),
(50, 'Estonian Kroon', 'EEK'),
(51, 'Ethiopian Birr', 'ETB'),
(52, 'Euro', 'EUR'),
(53, 'Falkland Islands Pound', 'FKP'),
(54, 'Fijian Dollar', 'FJD'),
(55, 'Gambian Dalasi', 'GMD'),
(56, 'Georgian Lari', 'GEL'),
(57, 'German Mark', 'DEM'),
(58, 'Ghanaian Cedi', 'GHS'),
(59, 'Gibraltar Pound', 'GIP'),
(60, 'Greek Drachma', 'GRD'),
(61, 'Guatemalan Quetzal', 'GTQ'),
(62, 'Guinean Franc', 'GNF'),
(63, 'Guyanaese Dollar', 'GYD'),
(64, 'Haitian Gourde', 'HTG'),
(65, 'Honduran Lempira', 'HNL'),
(66, 'Hong Kong Dollar', 'HKD'),
(67, 'Hungarian Forint', 'HUF'),
(68, 'Icelandic KrÃ³na', 'ISK'),
(69, 'Indian Rupee', 'INR'),
(70, 'Indonesian Rupiah', 'IDR'),
(71, 'Iranian Rial', 'IRR'),
(72, 'Iraqi Dinar', 'IQD'),
(73, 'Israeli New Sheqel', 'ILS'),
(74, 'Italian Lira', 'ITL'),
(75, 'Jamaican Dollar', 'JMD'),
(76, 'Japanese Yen', 'JPY'),
(77, 'Jordanian Dinar', 'JOD'),
(78, 'Kazakhstani Tenge', 'KZT'),
(79, 'Kenyan Shilling', 'KES'),
(80, 'Kuwaiti Dinar', 'KWD'),
(81, 'Kyrgystani Som', 'KGS'),
(82, 'Laotian Kip', 'LAK'),
(83, 'Latvian Lats', 'LVL'),
(84, 'Lebanese Pound', 'LBP'),
(85, 'Lesotho Loti', 'LSL'),
(86, 'Liberian Dollar', 'LRD'),
(87, 'Libyan Dinar', 'LYD'),
(88, 'Lithuanian Litas', 'LTL'),
(89, 'Macanese Pataca', 'MOP'),
(90, 'Macedonian Denar', 'MKD'),
(91, 'Malagasy Ariary', 'MGA'),
(92, 'Malawian Kwacha', 'MWK'),
(93, 'Malaysian Ringgit', 'MYR'),
(94, 'Maldivian Rufiyaa', 'MVR'),
(95, 'Mauritanian Ouguiya', 'MRO'),
(96, 'Mauritian Rupee', 'MUR'),
(97, 'Mexican Peso', 'MXN'),
(98, 'Moldovan Leu', 'MDL'),
(99, 'Mongolian Tugrik', 'MNT'),
(100, 'Moroccan Dirham', 'MAD'),
(101, 'Mozambican Metical', 'MZM'),
(102, 'Myanmar Kyat', 'MMK'),
(103, 'Namibian Dollar', 'NAD'),
(104, 'Nepalese Rupee', 'NPR'),
(105, 'Netherlands Antillean Guilder', 'ANG'),
(106, 'New Taiwan Dollar', 'TWD'),
(107, 'New Zealand Dollar', 'NZD'),
(108, 'Nicaraguan CÃ³rdoba', 'NIO'),
(109, 'Nigerian Naira', 'NGN'),
(110, 'North Korean Won', 'KPW'),
(111, 'Norwegian Krone', 'NOK'),
(112, 'Omani Rial', 'OMR'),
(113, 'Pakistani Rupee', 'PKR'),
(114, 'Panamanian Balboa', 'PAB'),
(115, 'Papua New Guinean Kina', 'PGK'),
(116, 'Paraguayan Guarani', 'PYG'),
(117, 'Peruvian Nuevo Sol', 'PEN'),
(118, 'Philippine Peso', 'PHP'),
(119, 'Polish Zloty', 'PLN'),
(120, 'Qatari Rial', 'QAR'),
(121, 'Romanian Leu', 'RON'),
(122, 'Russian Ruble', 'RUB'),
(123, 'Rwandan Franc', 'RWF'),
(124, 'Salvadoran ColÃ³n', 'SVC'),
(125, 'Samoan Tala', 'WST'),
(126, 'Saudi Riyal', 'SAR'),
(127, 'Serbian Dinar', 'RSD'),
(128, 'Seychellois Rupee', 'SCR'),
(129, 'Sierra Leonean Leone', 'SLL'),
(130, 'Singapore Dollar', 'SGD'),
(131, 'Slovak Koruna', 'SKK'),
(132, 'Solomon Islands Dollar', 'SBD'),
(133, 'Somali Shilling', 'SOS'),
(134, 'South African Rand', 'ZAR'),
(135, 'South Korean Won', 'KRW'),
(136, 'Special Drawing Rights', 'XDR'),
(137, 'Sri Lankan Rupee', 'LKR'),
(138, 'St. Helena Pound', 'SHP'),
(139, 'Sudanese Pound', 'SDG'),
(140, 'Surinamese Dollar', 'SRD'),
(141, 'Swazi Lilangeni', 'SZL'),
(142, 'Swedish Krona', 'SEK'),
(143, 'Swiss Franc', 'CHF'),
(144, 'Syrian Pound', 'SYP'),
(145, 'São Tomé and Príncipe Dobra', 'STD'),
(146, 'Tajikistani Somoni', 'TJS'),
(147, 'Tanzanian Shilling', 'TZS'),
(148, 'Thai Baht', 'THB'),
(149, 'Tongan paanga', 'TOP'),
(150, 'Trinidad & Tobago Dollar', 'TTD'),
(151, 'Tunisian Dinar', 'TND'),
(152, 'Turkish Lira', 'TRY'),
(153, 'Turkmenistani Manat', 'TMT'),
(154, 'Ugandan Shilling', 'UGX'),
(155, 'Ukrainian Hryvnia', 'UAH'),
(156, 'United Arab Emirates Dirham', 'AED'),
(157, 'Uruguayan Peso', 'UYU'),
(158, 'US Dollar', 'USD'),
(159, 'Uzbekistan Som', 'UZS'),
(160, 'Vanuatu Vatu', 'VUV'),
(161, 'Venezuelan BolÃ­var', 'VEF'),
(162, 'Vietnamese Dong', 'VND'),
(163, 'Yemeni Rial', 'YER'),
(164, 'Zambian Kwacha', 'ZMK');

INSERT INTO `product` (`id`, `name`, `brand`, `description`, `category_id`, `price`, `created_at`, `updated_at`, `isActive`) VALUES
(1, 'Acer Aspire XC-1660 Desktop computer i5/8/512', 'Acer', 'This Acer Aspire XC-1660 desktop computer has a nice, black case. The powerful performance is ensured by an 11th gen.Intel® processor. The comprehensive connectivity options allow you to connect your accessories and customize the user experience to your needs.\r\n\r\n11th gen. Core i5\r\nGet plenty of computing power with your computer\'s 11th generation Intel® Core processor. This processor can easily handle several demanding tasks simultaneously. The i5-11400 processor runs 2 threads per second. core and can run up to 4.4 Ghz. The processor is accompanied by 8 GB of DDR4 RAM, so you can switch between different programs without lagging.\r\n\r\nSSD storage\r\nDo not waste time waiting for an application to load. 512 GB M.2 PCIe NVMe SSD storage handles booting and loading in seconds.\r\n\r\nHDMI\r\nThe HDMI output can be connected to an HD-compatible TV or projector to display 4K resolution images and videos on a large screen.\r\n\r\nQuick connections\r\n- 2x HDMI2.0b ports\r\n- 2x USB-A 3.2 Gen1 ports\r\n- 1x USB-A 3.2 Gen 2 port\r\n- 1x USB-C 3.2 Gen2 port\r\n- 4x USB 2.0 ports\r\n- Lightning fast wi-fi-ac, Bluetooth 5.0, Gigabit Ethernet port\r\n- 3.5 mm out for headphones, 3.5 mm audio in, 3.5 mm audio out, 2x 3.5 mm microphone in\r\n\r\nOther features\r\n- Windows 10 Home 64-bit\r\n- 180 W Power supply (80 Plus Bronze) The\r\n', 2, 3499, '2021-12-14 18:55:49', '2021-12-14 19:36:37', 1),
(2, 'iMac 24\" 8C CPU/7C GPU/256 (blue)', 'Apple', 'This iMac 24 ”is built around the M1 processor, which ensures ultra-high performance for video editing, audio processing and gaming at console level. The 6-speaker system has 2 subwoofers that produce rich sound to match movies and music streaming. At the same time, the impact on the environment is minimized with the environmentally friendly and recyclable materials.\r\n\r\nApple M1 system-on-chip\r\nThis iMac features Apple\'s specially designed Apple M1 system-on-chip with octa-core CPU and 7-core GPU, built on a revolutionary 5nm process that makes it possible to utilize 16 billion transistors to create amazing performance and power efficiency. It also has Neural Engine and a unified memory architecture, so it can create a unified cache that can be accessed instantly across the chip. Get ready for lightning-fast image / video processing, rendering and an immersive gaming experience.\r\n\r\nRetina 4.5K display\r\nExperience ultra-fine details. The 24 ”Retina 4.5K screen has 4480 x 2520 resolution, a total of over 11 million individual pixels. The screen has 500 nit volume and supports wide P3 color profile with 1 billion colors. The monitor supports your work, from 3-D modeling design to image editing and video processing and more.\r\n\r\n1080p FaceTime HD Camera\r\nThe device features a 1080p FaceTime HD camera, the best Mac camera to date that delivers stunningly detailed video in conjunction with the M1 processor\'s advanced image signal processor.\r\n\r\nThunderbolt 3 / USB 4.0\r\nThis iMac has 2 reversible Thunderbolt 3 ports with up to 40 Gbps transfer speeds that act as a multifunctional connection between MacBook and external devices. The ports support DisplayPort video output for 1x external 6K monitor at 60 Hz or 2x external 4K DCI monitors at 60 Hz.\r\n\r\nmacOS Big Sur The\r\ncomputer\'s Next-gen macOS Big Sur is dedicated to using your iMac more intuitively so you can control its full potential. Thanks to the many small improvements over the previous version of macOS, an already excellent operating system is even better. Advances in applications like Safari and Notes make everyday work easier, and Apple Music with Apple TV makes the computer suitable for leisure use.\r\n\r\nMore features\r\n- 256 GB SSD storage\r\n- 2x USB 4 / Thunderbolt 3 ports\r\n- Lightning fast wi-fi-ax, Bluetooth 5\r\n- 1080p FaceTime HD camera with Apple M1 enhanced image processing\r\n- 6-speaker system, triple microphone setup\r\n- 3.5 mm mini-jack output\r\n\r\nIncluded in the package\r\n- Magic Keyboard\r\n- Magic Mouse\r\n- 143 W power adapter\r\n- Power cable\r\n- USB-C to Lightning cable', 2, 11499, '2021-12-14 19:36:00', '2021-12-14 19:36:00', 1),
(3, 'Lenovo IdeaCentre 3 Desktop computer', 'Lenovo', 'With this Lenovo IdeaCentre 3 desktop computer, your family can easily access their favorite media, photos, videos, documents and more. The computer is equipped with a 7 liter case that fits anywhere. The case is equipped with 4 USB ports on the front and you can easily connect your external devices without too much hassle on the back. With the convenient Lenovo Family Cloud service, you and your family can access your data on the cloud server via smartphone, no matter where you are.\r\n\r\nAMD processor\r\nThe computer is equipped with an AMD Ryzen 5 quad-core processor, which can run several demanding programs at a time. When more power is needed, the processor can switch to up to 3.7 GHz turbo mode. The processor is followed by 16 GB of fast DDR RAM as well as the onboard AMD Radeon Vega 8 graphics chip, which lets you play games at low to medium settings.\r\n\r\nSSD storage\r\nYour computer uses lightning-fast 512 GB SSD storage that lets you boot the system or open games in seconds.\r\n\r\nLenovo Family Cloud Storage\r\nWith Lenovo Family Cloud Storage, your entire family can easily store their favorite media and access it with the free Lenovo Family Cloud app for iOS and Android devices.\r\n\r\nHDMI\r\nThe HDMI output can be connected to an HD TV or projector, so you can view images and video in Full HD resolution on a larger screen.\r\n\r\nConnections:\r\n- 1x VGA,\r\n- 1 x HDMI\r\n- 2x USB-A 3.1 Gen1 ports\r\n- 6x USB-A 2.0 ports\r\n- Dual band wi-fi-ac, Gigabit LAN port, Bluetooth 5.0\r\n\r\nOther features:\r\n- Realtek ALC222-CG integrated sound card with HD audio output\r\n- Microsoft Windows 10 Home 64-bit', 2, 4499, '2021-12-14 19:37:55', '2021-12-14 19:37:55', 1),
(4, 'Acer Aspire XC-830 Desktop Computer CEL/4/128', 'Acer', 'The desktop Acer Aspire XC-830 computer is a great choice for your computer work. The Intel® Celeron® processor delivers competent, stable performance for everyday computing tasks. The comprehensive connection options make it possible to connect your favorite accessories and adapt the experience to your needs.\r\n\r\nHigh efficiency The\r\ncomputer\'s dual-core Intel® Celeron® processor from the Gemini Lake family can switch to turbo mode for more demanding tasks or apps. With the 10 W power supply, the computer is also energy efficient, ideal for low power solutions. The processor is followed by 4 GB of fast DDR4 RAM and integrated Intel UHD Graphics 600.\r\n\r\nSSD storage\r\n128 GB M.2 PCIe NVMe SSD storage handles booting and loading in a matter of seconds.\r\n\r\nHDMI\r\nThe HDMI output can be connected to an HD-compatible TV or projector, so you can view images and videos in 4K resolution on a large screen.\r\n\r\nFast connections\r\n- 1x HDMI 1.4b port, 1x VGA\r\n- 2x USB-A 3.2 Gen1 ports\r\n- 4x USB 2.0 ports\r\n- Lightning fast wi-fi ac, Bluetooth 4.2, Gigabit Ethernet port\r\n- Micro SDXC card port -\r\n3.5mm out for headphones , 3.5 mm audio in, 3.5 mm audio out, 2x 3.5 mm microphone in\r\n\r\nOther features\r\n- Windows Professional 64-bit\r\n- 65W power supply', 2, 2099, '2021-12-14 20:19:15', '2021-12-14 20:19:15', 1),
(5, 'PlayStation 5 (PS5)', 'PlayStation', 'PlayStation 5 redefines gaming with a range of next-generation features that provide an excellent gaming experience. Experience fluid gameplay at 120 fps in compatible games with support for 120 Hz output on 4K screens. Feel the action in the game with the redesigned DualSense wireless controller, which incorporates haptic feedback vibrations and adaptive triggers that together deliver next-level sensory feedback from in-game actions.\r\n\r\nProcessor and graphics power\r\nThe photorealistic next-generation graphics are made possible by a combination of components designed specifically for Playstation 5. The power is provided by a special AMD Ryzen Zen 2 x86-64 processor with 8-cores / 16-threads configuration with a variable frequency of up to 3.5 GHz and AMD Radeon RDNA-2 AMD based graphics with a variable frequency of up to 2.23 GHz (36 CU, 10.3 TFLOPS) with the support of true Ray-Tracing Acceleration. The system is followed by lightning fast 16 GDDR6 RAM with 448 GB / s bandwidth.\r\n\r\n4K and 8K entertainment\r\nPlaystation 5 can deliver 4K UHD (up to 120 Hz) and up to 8K 4320p resolution. So you can get the best possible image quality.\r\n\r\nHDR support\r\nThanks to High Dynamic Range picture technology, users with HDR-compatible TVs can enjoy deeper contrast, vibrant colors and more realistic environments in compatible games and other content.\r\n\r\nUltra-fast SSD\r\nSlip for long waits. Playstation 5 has a particularly ultra-fast 825 GB SSD with up to 5.5 GB / s read speed, which ensures near-instant loading and faster installation times for games and patches. It is now possible to game within seconds after booting the console.\r\n\r\nDualSense wireless controller\r\nTake control with the enhanced DualSense wireless controller. The haptic feedback vibration technology and the adaptive trigger buttons (R2 / L2) provide detailed sensory feedback. The controller has a rechargeable battery, a larger touchpad, 6-axis motion sensing system, sound jack output, USB-C port and built-in microphone and speaker.\r\n\r\nTempest 3D AudioTech\r\nTempest 3D AudioTech is a dedicated sound processor engine that can create 3-dimensional surround sound with hundreds of sound sources, giving the impression that the sound is coming from any direction. And you can enjoy the sound via headphones or your TV speakers in supported games.\r\n\r\nReady for action\r\nPlaystation 5 allows you to download or update games in the background, even in standby mode. Get rid of waiting for long game updates. You can start playing after only part of the game data has been downloaded. The PlayGo feature downloads the rest of the game in the background while you play.\r\n\r\nShare\r\nShow your epic triumphs at the touch of a button. Just press the Create button on the controller, scan through the last minute gameplay, take it and return to the game - the video will be uploaded while you play. The Playstation 5 system can broadcast your gameplay in real time.\r\n\r\nSupported formats - Blu-ray optical drive\r\n- Ultra HD Blu-ray (66G / 100G)\r\n- 10x CAVBD-ROM (25G / 50G)\r\n- 8xCAVBD-R / RE (25G / 50G)\r\n- 8xCAVDVD\r\n- 3.2xCLV\r\n\r\nPorts\r\n- HDMI 2.1 with 4K 120 Hz, 8K, VRR output\r\n- 1x USB-C 3.2 Gen2 (front)\r\n- 2x USB-A 3.2 Gen2 (rear)\r\n- 1x USB-A 3.2 Gen1 (front)\r\n- Gigabit LAN Ethernet port\r\n- Wi- fi-ax and Bluetooth 5.1\r\n\r\nIncluded accessories\r\n- DualSense wireless controller\r\n- HDMI cable\r\n- USB charger cable\r\n- Power cord', 3, 4199, '2021-12-14 21:34:31', '2021-12-14 21:34:31', 1),
(6, 'Xbox Series S 512 GB (white)', 'Xbox', 'Play with the best on the Xbox Series S game console, which has a modern and compact design. Xbox Velocity Architecture with 4 teraflops of graphics processor power and 10 GB of graphics memory, so you can enjoy the latest titles at up to 120 fps, while 3D Spatial Audio with Dolby 5.1 offers ultra-high sound quality. You can play thousands of games thanks to the backward compatibility all the way back to the original Xbox.\r\n\r\nPerformance\r\nXbox Velocity Architecture delivers incredible finesse and detail when playing in 1440p. Enjoy up to 120 fps and forget about lost frames, screen tearing or visual artifacts.\r\n\r\nAudio\r\n3D Spatial Audio technology uses Dolby Digital 5.1 audio output with Atmos enhancement for maximum immersion in digital worlds and perfect representation of movies and video audio.\r\n\r\nXbox One Compatibility\r\nYour current Xbox One accessories, controllers and gadgets are fully compatible with the new Xbox Series S - just plug them in.\r\n\r\nGame Library The\r\nXbox Series S has a number of Xbox Series S Enhanced titles that are optimized to take advantage of its excellent performance. Now you can also play thousands of Xbox One, Xbox 360 and original Xbox games with improved quality.\r\n\r\nController\r\nThe wireless controller has a streamlined and ergonomic shape with a textured surface to ensure a firm grip, long wireless range and the ability to capture and share content.\r\n\r\nStorage\r\nThe 512 GB hard drive allows you to store a lot of high-end games at the same time - no need to uninstall your favorites to make room for a new game. You can also purchase the Seagate Storage Expansion Card for 1TB of extra storage without compromising on performance.\r\n\r\nThe box contains:\r\n- Xbox Series S console\r\n- Xbox wireless controller\r\n- Ultra High Speed ​​HDMI cable', 3, 2399, '2021-12-14 21:34:31', '2021-12-14 21:34:31', 1),
(7, 'Xbox Series X 1 TB (black)', 'Xbox', 'Take your gaming to a new level with this Xbox Series X gaming console. The ultra-high performance is ensured by Xbox Velocity Architecture, 12 teraflops of graphics processor power and 16 GB of graphics memory. Play and stream in true 4K resolution and experience amazingly detailed worlds enhanced by HDR technology. Immerse yourself in the game with the perfect Dolby TrueHD sound. And plunge into a range of experiences thanks to the built-in Blu-ray player and backward compatibility with thousands of games across 4 generations of Xbox consoles.\r\n\r\nTrue 4K gaming\r\nXbox Velocity Architecture delivers incredible finesse and detail when playing in 4K. Enjoy up to 120 fps and forget about lost frames, screen tearing or visual artifacts.\r\n\r\nHDR\r\nWith support for up to 8K High Dynamic Range, you can experience clearer colors and deeper contrasts in compatible games, resulting in more vivid games.\r\n\r\n4K UHD video The\r\n4K UHD resolution provides 4 times the level of detail of Full HD, ensuring exceptional entertainment quality when watching 4K content from Blu-ray discs or when streaming 4K video at 120 fps.\r\n\r\nAudio\r\nTrueHD Audio technology uses Dolby Digital 5.1 audio output with Atmos enhancement for maximum immersion in digital worlds and perfect representation of movies and video audio.\r\n\r\nXbox One Compatibility\r\nYour current Xbox One accessories, controllers and gadgets are fully compatible with the new Xbox Series X - just plug them in.\r\n\r\nGame library\r\nThe Xbox Series X features exclusive 4K games as well as a number of Xbox Series X Enhanced titles that are optimized to take advantage of its excellent performance. Now you can also play thousands of Xbox One, Xbox 360 and original Xbox games with improved quality.\r\n\r\nController\r\nThe wireless controller has a streamlined and ergonomic shape with a textured surface to ensure a firm grip, long wireless range and the ability to capture and share content.\r\n\r\nStoring the\r\n1 TB hard drive allows you to store a lot of high-end games at once - no need to uninstall your favorites to make room for a new game. You can also purchase the Seagate Storage Expansion Card for 1TB of extra storage without compromising on performance.\r\n\r\nThe box contains:\r\n- Xbox Series X console\r\n- Xbox trådløs controller\r\n- Ultra High Speed HDMI kabel', 3, 3899, '2021-12-14 21:34:31', '2021-12-14 21:34:31', 1),
(8, 'Microsoft Xbox Series X/S Wireless controller (robot white)', 'Xbox', 'The Xbox Wireless controller has a modernized design with an updated hybrid D-pad for even more precise control of your movements. The controller also has textured handles for triggers, bumpers and a back case for a safer grip. Thanks to the improved rumble triggers and haptic feedback vibration, you can immerse yourself even more and feel your in-game actions.\r\n\r\nReduced latency The\r\ncontroller has improved radio connectivity for even lower latency so you can gain an advantage. Data is now transferred just before a game requests it, so the controller is synchronized with the game for both analog and digital inputs and the prevention of unforeseen latency spikes.\r\n\r\nXbox Wireless and bluetooth technology\r\nThe controller has Xbox Wireless radio and Bluetooth Low energy technology for both wireless gaming on both Xbox Series X and S, the Xbox One family, Windows 10 PC as well as Android phones and tablets.\r\n\r\nShare button\r\nSharing content with your friends and followers is easy. Just click the Share button while playing and instantly share videos and screenshots from your gameplay across many social media platforms.\r\n\r\nBatteries The\r\ncontroller has 2 pre-installed AA batteries that fit inside the case, eliminating the need for additional battery packs.\r\n\r\nRange\r\nThe maximum wireless range of the controller is approximately 6 m, suitable for even larger spaces.\r\n\r\nHeadset connection\r\nThe 3.5 mm mini-jack port allows you to connect your headset directly to the controller.', 3, 499, '2021-12-14 21:34:31', '2021-12-14 21:34:31', 1),
(9, 'DualShock 4 controller PS4 (black)', 'PlayStation', 'The DualShock 4 controller for PlayStation 4 is equipped with new innovations to deliver more immersive gaming experiences. Features include a highly sensitive six-axis sensor as well as a touch pad located on top of the controller, which offers completely new ways to play and interact with games. The new Share button makes video streaming and sharing just a tap away.\r\n\r\nShare button. Why not share your triumphs and achievements with friends via popular social networks at the touch of a button?\r\n\r\nBuilt-in mono speaker and headset jack. Make the details stand out. Enjoy hifi sound effects through the controller and chat with friends online via a headset.\r\n\r\nImproved vibration.You will not only be able to see and hear everything in even deeper detail, you will also feel it, thanks to the intense vibration motors.\r\n\r\nTouch Pad. Guide, move or draw with the Touch Pad. Located on the front of the controller, it will free up the way you play.\r\n\r\nLight Bar. Four colored LEDs provide a simple way to identify players and quickly see useful game information, such as when a character is seriously injured.', 3, 597, '2021-12-14 21:34:31', '2021-12-14 21:34:31', 1),
(10, 'PS5 DualSense controller (white)', 'PlayStation', 'Take control of the enhanced DualSense wireless controller for PlayStation 5. The haptic feedback vibration technology and adaptive trigger buttons (R2 / L2) provide detailed sensory feedback that simulates in-game action.\r\n\r\nMore features\r\n- Create button lets you share your gaming experience directly with your friends\r\n- 3.5mm mini-jack input for headsets and a dedicated mute button\r\n- USB-C port for wired connection and charging\r\n- Built-in 6-axis motion sensor , accelerometer and gyroscope capture motion and rotation from the controller\r\n- Built-in speaker and microphone', 3, 699, '2021-12-14 21:34:31', '2021-12-14 21:34:31', 1),
(11, 'iPhone 13 – 5G smartphone 128GB Midnight', 'Apple', 'The iPhone 13 smartphone impresses with its fantastically fast A15 Bionic processor, 5G data connection and the beautiful 12MP dual camera with sensor-shift OIS. Then it picks up even more light and detail, even in dark areas. Thanks to the IP68 certification and the Ceramic Shield glass that covers the screen, you can take your phone on adventures without worries.\r\n\r\nClassic design with good wear resistance\r\niPhone 13 has a classic design with an aluminum frame and a glass back. To ensure even higher abrasion resistance for the device\'s touch screen, Apple has worked closely with Corning to develop a revolutionary glass technology - namely Ceramic Shield, which introduces nanoceramic crystals in glass. This iPhone also has IP68 rating, so it is spill resistant and can last for up to 30 minutes at 6 meters water depth.\r\n\r\nSuper Retina XDR display The\r\nSuper Retina XDR OLED touch screen extends from edge to edge and offers more space for content, while keeping the dimensions of the phone at a level where you can still use it in one hand. The 2560 × 1170 screen resolution with 460 ppi delivers a high level of detail as well as True Tone and HDR technology for precise colors. With a maximum brightness of 800 nits in typical use and 1,200 nits for HDR content, everything can be seen clearly in the images, even on a sunny day.\r\n\r\nPowerful processor\r\nThe A15 Bionic processor offers a 6-core CPU with 2 performance and 4 efficiency cores, as well as a new 4-core graphics processor unit for an excellent gaming and multimedia experience and a new 16-core Neural Engine. Although it is a powerful device, it is also hugely power efficient thanks to the 5nm manufacturing process.\r\n\r\nDual camera system with Wide and Ultra Wide\r\niPhone 13 has a fantastic dual camera system with an Ultra Wide camera that allows you to take pictures and record 4K videos outside the frame - a feature that is perfect for taking pictures of landscapes, groups, decor and action. The Ultra Wide sensor now captures even more detail in dark areas. The second camera is a 12 MP wide-angle camera that takes well-lit pictures, even in low light, thanks to the new Night mode. It also has a new sensor-shift image stabilization feature for sharp images, even when the hand is shaking. The portrait mode with 6 effects and Depth Control can create more natural bokeh and provide more light control, so you can always take great pictures.\r\n\r\nCinematic mode for professional videos\r\nWhen recording videos, you can take advantage of the new Cinematic mode, which automatically shifts focus from one subject to another, creating beautiful depth effects and focus transitions. The camera also senses when a new subject enters the scene and shifts focus. Thanks to the good processing properties of the iPhone, you can even adjust your recordings after recording them. This technique allows you to create more professional content on your iPhone.\r\n\r\nTrueDepth front camera\r\nThe front-facing TrueDepth 12 MP camera can be used for stunning selfies and group photos full of vibrant colors. You can even use the front camera to take a slofie - a high-quality slow-motion selfie.\r\n\r\nNext-generation Smart HDR 4\r\nTake ultra-sharp images with Smart HDR 4, which uses machine learning to maximize the potential of each image and adjusts brightness, colors and white balance. So you can take great pictures and videos in all lighting conditions and with perfectly captured skin tones and textures.\r\n\r\niOS 15\r\niPhone 13 has enhanced iOS 15. With SharePlay, you can talk on FaceTime while watching TV shows and movies, listening to music, or sharing your screen. The grid mode shows the people on FaceTime in the same size, so you get better group conversations. The notifications have been redesigned and now show larger contact photos and app icons, making it easier to identify them.\r\n\r\nMore features\r\n- 128 GB internal memory\r\n- Dual SIM compatible with physical Nano SIM and virtual eSIM\r\n- More secure Face ID\r\n- Lightning fast WiFi 6, Bluetooth 5.0 and one-touch NFC pairing\r\n- MagSafe wireless charging up to 15 W - Qi wireless charging up to 7.5 W\r\n\r\nIn the box:\r\n- iPhone 13\r\n- USB-C for Lightning cable\r\n- Documentation', 9, 6999, '2021-12-14 22:29:01', '2021-12-14 22:29:01', 1),
(12, 'iPhone 13 Pro – 5G smartphone 128GB Graphite', 'Apple', 'Explore the world through the lens of the iPhone 13 Pro smartphone. It has a professional 12 MP triple camera with Wide, Ultrawide and telephoto sensors. Its industry-leading IP68 water resistance protects the phone from rainwater and water splashes. The A15 Bionic processor offers excellent performance, balanced power consumption and 5G data connectivity.\r\n\r\nClassic design with good wear resistance The\r\niPhone 13 Pro has a classic design with an aluminum frame and a glass back. To ensure even higher abrasion resistance for the device\'s touch screen, Apple has worked closely with Corning to develop a revolutionary glass technology - namely Ceramic Shield, which introduces nanoceramic crystals in glass. This iPhone also has IP68 rating, so it is spill resistant and can last for up to 30 minutes at 6 meters water depth.\r\n\r\nSuper Retina XDR display The\r\nSuper Retina XDR OLED touch screen extends from edge to edge and offers more space for content, while keeping the dimensions of the phone at a level where you can still use it in one hand. The 2560 × 1170 screen resolution with 460 ppi delivers a high level of detail as well as True Tone and HDR technology for precise colors. With a maximum brightness of 1,000 nits in typical use and 1,200 nits for HDR content, everything can be seen clearly in the images, even on a sunny day. Thanks to a 120Hz refresh rate, you can enjoy even better content, especially when playing games, watching videos or scrolling through your feed.\r\n\r\nPowerful processor\r\nThe A15 Bionic processor offers a 6-core CPU with 2 performance and 4 efficiency cores, as well as a new 4-core graphics processor unit for an excellent gaming and multimedia experience and a new 16-core Neural Engine. Although it is a powerful device, it is also hugely power efficient thanks to the 5nm manufacturing process.\r\n\r\nDual camera system with Wide and Ultra Wide\r\niPhone 13 Pro has a great triple camera system with an Ultra Wide camera that allows you to take pictures and record 4K videos outside the frame - a feature that is perfect for taking pictures of landscapes, groups, decor and action. The Ultra Wide sensor now captures even more detail in dark areas. The second camera is a 12 MP wide-angle camera that takes beautifully lit pictures, even in low light, thanks to the new Night mode and LiDAR Scanner. It also has a new sensor-shift image stabilization feature for sharp images, even when the hand is shaking. The portrait mode with 6 effects and Depth Control can create more natural bokeh and provide more light control, so you can always take great pictures. The telephoto lens provides 3x optical zoom.\r\n\r\nCinematic mode for professional videos\r\nWhen recording videos, you can take advantage of the new Cinematic mode, which automatically shifts focus from one subject to another, creating beautiful depth effects and focus transitions. The camera also senses when a new subject enters the scene and shifts focus. Thanks to the good processing properties of the iPhone, you can even adjust your recordings after recording them. This technique allows you to create more professional content on your iPhone.\r\n\r\nTrueDepth front camera\r\nThe front-facing TrueDepth 12 MP camera can be used for stunning selfies and group photos full of vibrant colors. You can even use the front camera to take a slofie - a high-quality slow-motion selfie.\r\n\r\nNext-generation Smart HDR 4\r\nTake ultra-sharp images with Smart HDR 4, which uses machine learning to maximize the potential of each image and adjusts brightness, colors and white balance. So you can take great pictures and videos in all lighting conditions and with perfectly captured skin tones and textures.\r\n\r\niOS 15\r\niPhone 13 Pro has enhanced iOS 15. With SharePlay, you can talk on FaceTime while watching TV shows and movies, listening to music, or sharing your screen. The grid mode shows the people on FaceTime in the same size, so you get better group conversations. The notifications have been redesigned and now show larger contact photos and app icons, making it easier to identify them.\r\n\r\nMore features:\r\n- 128GB internal memory\r\n- Dual SIM compatible with physical Nano SIM and virtual eSIM\r\n- More secure Face ID\r\n- Lightning fast WiFi 6, Bluetooth 5.0 and one-touch NFC pairing\r\n- MagSafe wireless charging up to 15 W\r\n- Qi wireless charging up to 7.5 W\r\n\r\nIn the box:\r\n- iPhone 13 Pro\r\n- USB-C for Lightning cable\r\n- Documentation', 9, 8999, '2021-12-14 22:29:01', '2021-12-14 22:29:01', 1),
(13, 'Samsung Galaxy S20 FE 4G smartphone 6/128GB (cloud navy)', 'Samsung', 'The Samsung Galaxy S20 FE smartphone combines powerful performance, AI camera processing for professional picture and video quality and a smooth gaming experience. It has a 6.5 ”SUPER AMOLED touch screen with foot Full HD + resolution and smooth 120 Hz refresh rate as well as a 12 + 12 + 8 MP triple camera. In addition, the smartphone has IP68 degree of protection. The Snapdragon 865 octa-core processor and the 6 GB RAM ensure smooth operation, even in demanding tasks.\r\n\r\nTouch screen\r\nGalaxy S20 FE has a flat 6.5 ”touch screen with Quad HD + resolution. Thanks to its Super AMOLED technology and HDR10 + support, you get sharp colors and deep black tones. But it is the 120 Hz refresh rate that makes the screen something very special. This means that the screen updates at 120 frames per second. second, which ensures smooth operation in, for example, games, videos or scrolling on social media. The screen is covered by durable Corning Gorilla Glass 3.\r\n\r\nCameras\r\nGalaxy S20 FE has a triple rear camera setup. The telephoto sensor has 8 MP resolution and f / 2.4 aperture. The 12 MP wide angle sensor has f / 1.8 aperture and OIS. The 12 MP ultra-wide angle sensor has an f / 2.2 aperture. The camera makes it possible to take pictures in circumstances that would have made it difficult in the past, thanks to 30x digital Space Zoom, 3x optical zoom and AI zoom technology as well as optical image stabilization. Thanks to the powerful AI and high light efficiency, you can count on professional results. The setup is followed by a flash. When capturing the moment, the camera can take several pictures, after which AI selects the 5-14 best pictures. Its 32 MP selfie camera is hidden in the screen\'s punch hole, but is also an interesting design element.\r\n\r\nPerformance and storage\r\nThe smartphone has a Qualcomm Snapdragon 865 octa-core processor combined with 6 GB of RAM. Thanks to the processor\'s energy efficiency and AI properties, you get powerful operation for any task. Your data can be stored in the internal 128 GB storage, which can be expanded with a microSD card of up to 1 TB.\r\n\r\nBattery safety\r\nThe device has a 4,500 mAh battery with 15 W Fast Charging support. The battery can be charged through the USB-C connector. The phone also supports 15 W wireless charging and has a Wireless PowerShare feature that allows you to use your phone as a fast charger for other compatible devices.\r\n\r\nSecurity\r\nTo unlock your phone, you can either use its reliable in-display fingerprint reader or or the selfie camera. To ensure better usability for businesses, the phone also has the reliable data security platform Samsung Knox.\r\n\r\nOther features\r\n- Wi-Fi 6, Wi-Fi Direct\r\n- Bluetooth 5.0\r\n- IP68 protection level (1.5 m water depth for 30 minutes)\r\n- NFC for seamless, contactless payments\r\n- GPS, GLONASS location services\r\n- Stereo speakers', 9, 2999, '2021-12-14 22:29:01', '2021-12-14 22:29:01', 1),
(14, 'Samsung Galaxy S21 Ultra 5G 12/128GB (phantom black)', 'Samsung', 'The Samsung Galaxy S21 Ultra smartphone offers a powerful 5mn Samsung Exynos 2100 processor with 5G, a 108 + 10 + 10 + 12Mpx camera with laser focus, speakers that are fine-tuned by AKG water and dust resistance with IP68 code. All in all, an excellent multimedia device with the power for any type of task.\r\n\r\nTouch screen\r\nGalaxy S21 Ultra offers a magnificent visual experience with its 6.8 \"touch screen with Quad HD + resolution of 3200 x 1440 pixels and a 20: 9 aspect ratio. The screen has solid 120 Hz refresh rate and Dynamic AMOLED resolution with colors and high quality contrast.Thanks to these modern technologies you can enjoy high quality content and\r\n\r\ngames.Cameras\r\nThe back has a 108 + 10 + 10 + 12Mpx camera with laser focus and a 108Mpx wide primary sensor with f / 1.8 aperture, autofocus and OIS followed by a 10Mpx telephoto sensor with f / 2.4 aperture and up to 100x zoom, another 10Mpx telephoto sensor with f / 4.9 aperture and OIS, and a 12Mpx ultra-wide camera with f / 2.2 aperture and autofocus. A 40Mpx camera with f / 2.2 aperture focus and autofocus is ready to take pictures.\r\n\r\nPerformance and storage\r\nUnder the cover knocks a new Samsung Exynos 2100 5nm octa-core processor with high performance, high efficiency and support for 5G networks. The processor is accompanied by 12 GB of RAM and your data can be stored in the internal 128 GB of memory.\r\n\r\nBattery\r\nThe device has a powerful 5,000 mAh battery with lightning fast charging and fast wireless charging support. Thanks to Wireless PowerShare, you can use your phone to charge other compatible devices wirelessly.\r\n\r\nMore information\r\n- USB-C v3.2 port\r\n- Bluetooth 5.0\r\n- NFC\r\n- Wi-Fi 6E\r\n- GPS\r\n- In-display ultrasonic fingerprint reader\r\n- Dolby Atmos support\r\n- Sound from AKG\r\n- IP68 water and dust resistance\r\n- Samsung Knox security platform', 9, 9799, '2021-12-14 22:29:01', '2021-12-14 22:29:01', 1),
(15, 'Apple AirPods (2019)', 'Apple', 'Listen to your favorite artists and your favorite music with the new, fully wireless Apple AirPods headphones. Their ultra-compact design and the absence of cables make them comfortable and easy to wear. The dual optical sensors with accelerometer sense when you take your AirPods in or out of your ears and start or pause playback automatically.\r\n\r\nSiri voice control\r\nUse the voice control with Siri to control playback, adjust the volume, check the battery life of your AirPods or ask the virtual assistant for advice and information - from the weather forecast or route to the day program for the day. The voice-detecting microphones with beamforming technology ensure crystal clear voice recognition so you don\'t even have to take your iPhone out of your pocket.\r\n\r\nTouch control\r\nAnswer or end a double-touch call on an AirPod. It does not matter if you use both AirPods or just one as a handsfree - the speaker and microphone work the same way.\r\n\r\nConnectivity and Compatibility\r\nAirPods use Apple\'s enhanced H1 chip for lightning-fast pairing with your iPhone. You can also connect them to other audio devices with Bluetooth wireless transmission such as older iPhone models, Mac computers, iPad or iPod touch. The new Airpods are compatible with iPhone, iPad or iPod touch devices running iOS 12.2 or later, Apple Watch with watchOS 5.2 or later, and Mac devices with macOS 10.14.4 or later.\r\n\r\nMating and integration\r\nIt\'s easy to pair your AirPods with your iPhone. Simply hold the charging case next to your iPhone for a short time and tap \"connect\" on the screen. When you take your AirPods out of the case, they turn on and pair automatically with the paired iPhone. They are also set up for automatic use with your Apple Watch, Mac or iPad through iCloud integration.\r\n\r\nSound quality\r\nThe music is streamed in AAC format in high quality, so you can enjoy your favorite music or your favorite artists to the fullest.\r\n\r\nBattery life\r\nWhen fully charged, these AirPods offer up to 5 hours of battery life or up to 3 hours of talk time - something of a feat when you consider their small dimensions. The included, charging case ensures multiple charges of your AirPods, so you can enjoy up to 34 hours of total usage time. Just 15 minutes in the charging case provides 3 hours of extra music playback time.\r\n\r\nWireless charger case\r\nThe wireless charger case can be charged via the Lightning connector on the bottom.\r\n\r\nIncluded\r\n- AirPods (2019 model)\r\n- Wireless charger case (charging via lightning cable)\r\n- Lightning-to-USB cable', 4, 1079, '2021-12-14 23:47:15', '2021-12-14 23:47:15', 1),
(16, 'Apple AirPods 3. gen. (2021)', 'Apple', 'With the new Apple AirPods 3rd gen. Wireless headphones do not make it easier to listen to your favorite music. Their ultra-compact design and lack of charges make it easy and comfortable to wear them in the ears. The headphones have spatial sound with dynamic head tracking, which makes you sense the sound from all directions.\r\n\r\nSpatial sound\r\nGet the best sound when watching movies or series with your AirPods in your ears. With dynamic head tracking, built-in gyroscopes and accelerometers, AirPods track the movements of your head, giving you the feeling that sound is coming from all directions and is all around you.\r\n\r\nSiri voice control\r\nUse your voice to operate these AirPods with Siri. Play songs again, turn up and down the volume, check the battery, or ask the virtual assistant for advice or information (everything from the weather to directions). Voice-capturing microphones with columnar technology ensure crystal clear voice recognition. You do not even have to take your iPhone out of your pocket.\r\n\r\nPressure sensor\r\nMake calls or operate your music with a button on the headphone. Whether you use both AirPods or just one, the headset and microphone work the same way.\r\n\r\nConnectivity and compatibility\r\nThese AirPods use Apple\'s extended H1 chip with super-fast pairing with your iPhone. You can also connect them to other audio devices (such as older iPhone models, Mac computers, iPad or iPod touch) via Bluetooth wireless transfer. These AirPods are compatible with iPhone, iPad, or iPod touch devices running iOS 12.2 or later, Apple Watch running watchOS 5.2 or later, and Mac running MacOS 10.14.4 or later.\r\n\r\nMating\r\nPairing your AirPods with your iPhone couldn\'t be easier. Just hold your charging case close to your iPhone for a short time, then tap \"connect\" on the screen. When you take your AirPods out of their case, they automatically turn on and connect to the iPhone to which they are paired. These AirPods are also automatically set up for use with your Apple Watch, Mac or iPad through iCloud.\r\n\r\nSweat and water resistant\r\nThese new AirPods stay by your side, even through the hardest workouts, and you do not have to worry about them getting wet.\r\n\r\nBattery life\r\nWhen fully charged, AirPods can provide up to 6 hours of battery life, which is quite impressive for their size. The included wireless charging case gives AirPods a total listening time of 30 hours. You can get a full hour of extra listening time with 5 minutes of charging.\r\n\r\nMagSafe Wireless Charging Case The MagSafe Wireless Charging\r\nCase can be recharged by placing it on a MagSafe charger or a Qi-compatible wireless charger. You can also use the Lightning connector at the bottom.', 4, 1549, '2021-12-14 23:47:15', '2021-12-14 23:47:15', 1),
(17, 'Razer Deathadder V2 gaming mouse', 'Razer', 'Dominate your enemies with this Razer Deathadder V2 gaming mouse . This predator of a gaming mouse is designed to turn your enemies into dust thanks to a powerful sensor, more personal setting options and high-precision switches.\r\n\r\nFast as a cobra: With this mouse \'Razer Focus + optical sensor, you hit your enemies every time. The mouse has an IPS of up to 650 and is extremely accurate with a DPI sensitivity of up to as much as 20,000. The sensor synchronizes with your computer to deliver excellent responsiveness, and it automatically adapts to new surfaces. You can even set it to turn the switch on and off at a certain height above the surface.\r\n\r\nA loyal beast:This gaming mouse is equipped with 8 programmable buttons that you can domesticate as you wish. With the Razer Synapse 3 program, you can personally set each button on the mouse as you wish - you can even give them secondary functions.\r\n\r\nA dangerous acquaintance: Each button on the mouse is equipped with an ultra-responsive Razer optical switch, which instantly obeys all your commands. Thanks to the use of infrared light instead of physical contact, the mouse can respond to your orders within just 0.2 milliseconds. No one escapes.\r\n\r\nFits well in the hand:This Deathadder gaming mouse continues its predecessor tradition and has a reputable ergonomic design that adapts to your hand and your grip, allowing you to relax your hand while trapping your enemies. The cable does not pull the mouse unnecessarily and thanks to the feet covered in PTFE, the mouse slides easily over your mouse pad.\r\n\r\nAlways with you: Whether you are going to the LAN with your neighbor or abroad for a serious tournament, you can always have this loyal beast with you. The mouse is equipped with its own storage, where you can store up to 5 personal profiles, so you do not have to set it from new all the time.\r\n\r\nBath in its radiance:You can personally set the mouse\'s Chroma light and choose from 16.8 million colors. You can choose from special effects such as a pulse or cycle, and you can even sync mouse light with your other Razer devices via the Synapse 3 application.\r\n\r\nMore features:\r\n- True 20,000 DPI sensitivity with 99.6% resolution accuracy\r\n- Quick adjustment of sensitivity\r\n- 50 G acceleration\r\n- Advanced lift / landing height adjustment\r\n- Tactile scroll wheel\r\n- Durable handles on the underside\r\n- Buttons with up to 70 million clicks durability\r\n- Connector via 2.1 m long USB cable', 8, 349, '2021-12-14 23:57:51', '2021-12-14 23:57:51', 1),
(18, 'Apple Magic Mouse', 'Apple', 'With this Apple Magic Mouse you can say goodbye to the traditional design of your mouse clickable buttons. The mouse has mulititouch pads that allow movements with one or two fingers. That way, it becomes playfully easy to surf, browse, zoom, scroll and swipe. The laser sensor gives you fantastic precision on almost all surfaces. This device is designed so that both right-handed and left-handed people can use it. Its stylish design fits your MacBook perfectly, and will therefore give a complete, professional impression.\r\n\r\nMultitouch surface\r\nThe touch-sensitive surface covers the entire top of this Magic Mouse. You can both cut and right-click as you would with any normal mouse. But this mouse is much more than just normal. A swipe either right or left moves you between your tabs in your Safari browser, or the photos in iPhoto. If you run your finger vertically, you scroll through your open document. A double-tap with a finger zooms in on your image or PDF file, while a double-tap with two fingers opens Mission Control, giving you an overview of all your open apps. The intelligent technology that this mouse utilizes makes sure not to confuse a scroll and swipe with each other. Technology can even recognize your hand, as long as it rests on the mouse. The scroll-up and down function can only be used with Mac OS 10.11 or late / iPadOS13.4 on the mouse.\r\n\r\nUser setup\r\nMaybe you need a different kind of movement, for an action you perform often - a double-click instead of a single click - or to scroll instead of swiping. With this mouse you can easily set up the various actions, or switch left with right in System Preferences.\r\n\r\nBattery and charging\r\nThe mouse uses a built-in Li-ion battery, so you no longer have to think about buying new batteries. Just plug the mouse into your Mac\'s USB port, via the included USB-C Lightning cable, and the mouse will be fully charged in about 2 hours. After charging, you have a full month of battery life.\r\n\r\nWireless connection\r\nThis mouse connects to your Mac via Bluetooth. The connection has a range of up to 9 meters, so there is no need for any adapter, while also avoiding a mess of wires on your desk.\r\n\r\nCompatibility\r\nMac computer with Bluetooth, OS X 10.11 or later.', 8, 679, '2021-12-14 23:57:51', '2021-12-14 23:57:51', 1),
(19, 'Razer Ornata V2', 'Razer', 'The Razer Ornata V2 gaming keyboard helps you on your way in your gaming. It has mecha-membrane switches to ensure comfort and precision, fully programmable keys to give you an edge over the competition as well as adjustable Razer Chroma RGB lights that shine in 16.8 million colors. The keyboard also has a detachable palm rest, a Fn layer for multimedia control and a digital wheel.\r\n\r\nDesign The\r\nkeyboard is nice and well designed. It has a removable wrist rest in imitation leather for long gaming evenings as well as intelligent options for cable routing, so you can guide the cable in the direction that best suits your setup.\r\n\r\nMecha-membrane keyboard\r\nThe keyboard combines mechanical switches with a membrane keyboard to deliver the softness of a membrane and the tactile feel of a mechanical switch. No compromises - neither on comfort, speed nor response.\r\n\r\nFully programmable keys The\r\nkeyboard allows for custom macros and key bindings, which can be created via Razer Synapse 3. Each benefit counts in intense gaming, so make sure the keyboard works perfectly for you with full customization.\r\n\r\nMultimedia\r\nkeys and wheels For quick control of brightness, volume, music and more, the keyboard has a number of keys for multimedia control, including a digital wheel.\r\n\r\nRazer Chroma RGB\r\nThe programmable keys with 16.8 million colors and many lighting effects give your gaming setup a professional feel. The effects are adjusted for Chroma integrated games, so you can lift the mood. The keyboard can be synced with other Chroma RGB devices to match and work together. And if you want to design your own unique effect, you can use the Chroma Studio software.\r\n\r\nMore functions\r\n- Nordic layout\r\n- N-key roll over\r\n- Braided fiber cable', 5, 444, '2021-12-15 00:00:50', '2021-12-15 00:00:50', 1),
(20, 'Apple Magic numeric keyboard', 'Apple', 'Apple Magic numeric keypad makes typing even more precise and comfortable than before. The keyboard keys have a redesigned scissor mechanism so they feel more responsive and move straight and stable. The numeric keypad makes working with financial tasks or spreadsheets quick and easy, and the low, wedge-shaped design complements your Mac or iPad.\r\n\r\nBattery and charging: The keyboard has a built-in Li-ion battery, so you do not have to spend time replacing flat batteries. Connect the keyboard to your Mac\'s USB port via the included Lightning cable and charge it for about 2 hours - then you get a full month of wireless use. And of course, you can use the keyboard while it charges.\r\n\r\nWireless connection: The keyboard connects to your Mac or iDevice via Bluetooth with a range of up to 9 meters - you get rid of tangled wires and adapters.\r\n\r\nCompatibility :\r\n- Mac computer with Bluetooth, macOS 10.12.4 or later\r\n- iOS devices with iOS 10.3 or later\r\n\r\nKeyboard layout : English', 5, 999, '2021-12-15 00:00:50', '2021-12-15 00:00:50', 1),
(21, 'Asus Vivobook 17 X712 17\" laptop i5/8/512GB', 'Asus', 'This Asus Vivobook 17 X712 laptop combines elegance and performance in a sleek design with a 2.14 cm profile and a weight of only 2.3 kg. Steal attention with the stylish design and impressive performance powered by the 11th generation Intel® processor. Get ready to work or relax to all types of content on the beautiful 17 ”Full HD screen.\r\n\r\nIntel® 11th gen. processor\r\nWith the quad-core Intel® Core ™ i5 processor from the Tiger Lake family, built on the efficient 10nm SuperFin architecture, you can run several demanding applications simultaneously without experiencing lagging or delay - ideal for streaming or demanding mutitasking. The processor can switch to a fast turbo mode of up to 4.2 GHz and is followed by 8 GB of DDR4 RAM.\r\n\r\nFull HD 1080p screen\r\nThe 17.3 \"IPS LED display has a crystal clear and detailed Full HD 1080p resolution. The sleek edges maximize the available screen space without creating any distractions. IPS technology ensures deep contrasts, vibrant colors and wide viewing angles.\r\n\r\nSSD storage\r\n512 GB M 0.2 PCIe NVMe SSD storage perform booting and loading in a matter of seconds.\r\n\r\nHDMI port\r\nHDMI output can be connected to an HD TV or a projector to display images up to Full HD 1080p resolution on a large screen.\r\n\r\nConnections\r\n- 1x HDMI 1.4 output\r\n- 1x USB 3.2 Gen 1 Type-A port\r\n- 1x USB 3.2 Gen 1 Type-C port\r\n- 2x USB 2.0 Type-A ports\r\n- Built-in Micro SD memory card\r\nreader - Lightning-fast wi-fi-ax, Bluetooth 5.0\r\n- 3.5 mm combined headphone / microphone port\r\n\r\nOther features\r\n- Windows 10 Home 64-bit\r\n- Touchpad with multitouch capability\r\n- 3-cell li-ion battery\r\n- Audio from ICEpower\r\n\r\nIncluded in the package:\r\n- Charger\r\n- Instructions for use\r\n- Warranty certificate', 6, 5999, '2021-12-15 00:04:32', '2021-12-15 00:04:32', 1);
INSERT INTO `product` (`id`, `name`, `brand`, `description`, `category_id`, `price`, `created_at`, `updated_at`, `isActive`) VALUES
(22, 'Asus Chromebook C434, 14” 2-in-1 laptop', 'Asus', 'The Asus Chromebook Flip C434 14 ”2-in-1 laptop has an elegant quality design that you can take with you on the go. The computer is designed with a focus on portability with the 1.57 cm thin profile and the weight of only 1.45 kg. And the fully rotating Full HD touch screen hinge ensures even more versatility when you want to share content with colleagues or just enjoy multimedia in tablet mode.\r\n\r\nGoogle Chrome OS\r\nThere are many usable installed Google applications like Docs, Maps, Gmail, Pics and more - with millions more available online in the Google Play Store. The operating system excels with easy setup and automatic updates every 6 weeks for maximum user comfort and security.\r\n\r\nProcessor and graphics card\r\nThe computer has an Intel Core M3-8100Y dual core processor from the Amber Lake Y family that has a power consumption of just 4.5 W. With the on-demand turbo mode, the device is ready to run even very demanding apps and multimedia. It is followed by 8GB of LPDDR3 RAM and onboard Intel UHD Graphics 615.\r\n\r\nFull HD touch screen The\r\n14 \"IPS LED WideView touch screen has crystal clear and detailed Full HD 1080p resolution. The touch recognition lets you control the device like a tablet, ideal for reviewing photos or zoom in and out of the map. IPS technology ensures deeper contrast, brighter colors and wider viewing angles.\r\n\r\nLightweight and portable\r\nwith only 1.57 cm thickness and 1.45 kg weight suits Chromebook fit easily in your travel bag, backpack or suitcase.\r\n\r\n2-in -1-form\r\nThe best from laptops and tablets in one package. You can rotate the screen to switch between standard computer mode if you need to type and want easy touch control for multimedia. Turn the keyboard back and watch movies, play touch games or give amazing animated presentations.\r\n\r\nStorage\r\nThe fast 64 GB flash drive ensures smooth and fast boot of the operating system and applications in just a few seconds. You can also use 100 GB Google Drive cloud storage for 1 year for free.\r\n\r\nConnectivity\r\n- 2x reversible USB 3.0 ports\r\n- 1x full-sized USB 3.0\r\n- Fast wi-fi ac, Bluetooth 4.0\r\n- Micro SD memory card port\r\n- 3.5mm mini audio jack\r\n\r\nOther features\r\n- Integrated webcam with 720p HD resolution\r\n- Touchpad with multitouch\r\n- Backlit keyboard\r\n- 3-cell lithium-polymer battery with 48 WHr capacity', 6, 3499, '2021-12-15 00:04:32', '2021-12-15 00:04:32', 1),
(23, 'Samsung T35F 24\" monitor', 'Samsung', 'This Samsung T35F 24 \"monitor is easy to use and delivers a sharp and detailed image in a beautiful, frameless design. The monitor has Full HD resolution with a frame rate of 75 Hz and a response time of 5 ms, which ensures a 100% fluid image , which is further enhanced by AMD FreeSync technology. You just need to plug in the HDMI cable and let yourself enjoy the sharp and vivid images.\r\n\r\nFull HD IPS panel The\r\n24 \"IPS panel delivers a sharp Full HD 1080p resolution with a high level of detail. IPS technology ensures deeper contrasts, clearer colors and wider viewing angles.\r\n\r\nAMD FreeSync\r\nThis technology synchronizes the screen refresh rate with one of your graphics cards, minimizing delays, screen tearing and lag. You can therefore enjoy a crisp and fluid movement, no matter what.\r\n\r\nKey features:\r\n- 24 \"/ 60.96 cm diagonal IPS LED panel\r\n- Max. Supported resolution: 1920 x 1080\r\n- 16: 9 screen format\r\n- 1,000: 1 static contrast\r\n- 5 ms response time\r\n- 250 nit brightness\r\n\r\nConnection:\r\n- 1x HDMI 1.4 port\r\n- 1X VGA port\r\n\r\nErgonomics:\r\n- 178 ° / 178 ° viewing angle\r\n- 20 ° / -2 ° screen tilt\r\n- 100 x 100 VESA brackets for wall mounting\r\n\r\nIncluded in the package:\r\n- HDMI cable\r\n- Power cable', 7, 799, '2021-12-15 00:25:21', '2021-12-15 00:25:21', 1),
(24, 'Lenovo G24-10 24\" gaming monitor', 'Lenovo', 'Enjoy your gaming to the fullest with the Lenovo G24-10 24 \"gaming screen. With its 24\" 144 Hz panel, you can immerse yourself in games and experience great performance. The screen follows when every millisecond counts. The excellent performance, the almost borderless screen and the beautiful stand fit the screen to your gamer table.\r\n\r\nUpdate speed\r\nWith the 144 Hz TN panel, you get near-instant input. It\'s good for gamers where every millisecond counts.\r\n\r\nKey functions:\r\n- 24 ”TN LED panel\r\n- Max. supported resolution: 1920 x 1080\r\n- 16: 9 screen ratio\r\n- 1,000: 1 static contrast\r\n- 3,000,000: 1 dynamic contrast\r\n- 1 ms response time (extreme)\r\n- 300 nit clarity\r\n\r\nConnections:\r\n- 1x HDMI 2.0\r\n- 1X DisplayPort 1.4\r\n- 1x 3.5 mm audio jack\r\n\r\nErgonomics:\r\n-\r\n170/160 ° viewing angle - 22 ° / -5 ° screen tilt\r\n- 100 x 100 VESA wall mounting standard\r\n- TUV Eye Comfort certified\r\n\r\nIncluded in the package:\r\n- HDMI cable\r\n- Power cord', 7, 1099, '2021-12-15 00:25:21', '2021-12-15 00:25:21', 1);

INSERT INTO `product_image` (`id`, `product_id`, `imageFile`) VALUES
(1, 1, 'product/acer_aspire_1660_computer_1.webp'),
(2, 1, 'product/acer_aspire_1660_computer_2.webp'),
(3, 1, 'product/acer_aspire_1660_computer_3.webp'),
(4, 2, 'product/imac_24_1.webp'),
(5, 2, 'product/imac_24_2.webp'),
(6, 2, 'product/imac_24_3.webp'),
(7, 3, 'product/lenovo_idea_center_1.webp'),
(8, 3, 'product/lenovo_idea_center_2.webp'),
(9, 3, 'product/lenovo_idea_center_3.webp'),
(10, 4, 'product/acer_aspire_830_computer_1.webp'),
(11, 4, 'product/acer_aspire_830_computer_2.webp'),
(12, 4, 'product/acer_aspire_830_computer_3.webp'),
(13, 5, 'product/ps5_console.webp'),
(14, 6, 'product/xbox_s_512.webp'),
(15, 7, 'product/xbox_x_1.webp'),
(16, 8, 'product/xbox_xs_controller.jpg'),
(17, 9, 'product/ps4_controller.webp'),
(18, 10, 'product/ps5_controller.webp'),
(19, 11, 'product/iphone13_128_midnight.webp'),
(20, 12, 'product/iphone13_128_graphite.webp'),
(21, 13, 'product/samsung_g_s20_FE.webp'),
(22, 14, 'product/samsung_g_s21_ultra.webp'),
(23, 15, 'product/airpods_2019.webp'),
(24, 16, 'product/airpods_2021.webp'),
(25, 17, 'product/razer_da_v2.webp'),
(26, 18, 'product/apple_mouse.webp'),
(27, 19, 'product/razer_ornata_v2.jpg'),
(28, 20, 'product/apple_keyboard.webp'),
(29, 21, 'product/asus_vivobook_17.webp'),
(30, 22, 'product/asus_chromebook_c434.webp'),
(31, 23, 'product/samsung_t35f_24.webp'),
(32, 24, 'product/lenovo_g24-10_24.webp');

INSERT INTO `product_inventory` (`id`, `product_id`, `quantity`) VALUES
(1, 1, 10),
(2, 2, 10),
(3, 3, 10),
(4, 4, 10),
(5, 5, 10),
(6, 6, 10),
(7, 7, 10),
(8, 8, 10),
(9, 9, 10),
(10, 10, 10),
(11, 11, 10),
(12, 12, 10),
(13, 13, 10),
(14, 14, 10),
(15, 15, 10),
(16, 16, 10),
(17, 17, 10),
(18, 18, 10),
(19, 19, 10),
(20, 20, 10),
(21, 21, 10),
(22, 22, 10),
(23, 23, 10),
(24, 24, 10);